# Recurrent neural networks for H.P Lovecraft text generation

"The color out of space" is one of my favorite tales from Lovecraft, i will use it(as well as others as the call of cthulhu) to create a recurrent neural network in tensorflow that learns his style and generates new text in his style

This network is based off of Andrej Karpathy's [post on RNNs](http://karpathy.github.io/2015/05/21/rnn-effectiveness/) and [implementation in Torch](https://github.com/karpathy/char-rnn) and an example from "Deep Learning Nanodegree" on udacity. Also, some information [here at r2rt](http://r2rt.com/recurrent-neural-networks-in-tensorflow-ii.html) and from [Sherjil Ozair](https://github.com/sherjilozair/char-rnn-tensorflow) on GitHub. 

## General architecture using "Long short term memory" units in the recurrent layers

<img src="assets/charseq.jpeg" width="500">

In [49]:
import time
from collections import namedtuple

import numpy as np
import tensorflow as tf
from nltk.tokenize import word_tokenize
import nltk
import itertools

In [50]:
# Run only the  first time nltk is used to download language
#nltk.download()

#### Function that separates text into tokens(for whitespace characters, only new line is implemented, missing tabs and others=

In [51]:
def tokenize_text(text):
    text = text.replace("\n"," new_line_token ")
    tokens = []
    splitted =[[word_tokenize(w),' ']for w in text.split()]
    splitted = list(itertools.chain(*list(itertools.chain(*splitted))))
    
    token_list = []
    i = 0
    while i < len(splitted):
        if splitted[i] == "new_line_token":
            if   token_list[-1]==" ":
                token_list[-1] = splitted[i]
            else:
                token_list.append(splitted[i])
            i+=1
        else:
            token_list.append(splitted[i])
        i+=1
    
    return token_list
tokenize_text("Hello, my name is Luis Leal!\n\nFrom Guatemala")

['Hello',
 ',',
 ' ',
 'my',
 ' ',
 'name',
 ' ',
 'is',
 ' ',
 'Luis',
 ' ',
 'Leal',
 '!',
 'new_line_token',
 'new_line_token',
 'From',
 ' ',
 'Guatemala',
 ' ']

First we'll load the text file and convert it into integers for our network to use. Here I'm creating a couple dictionaries to convert the characters to and from integers. Encoding the characters as integers makes it easier to use as input in the network.

In [52]:
with open('colour_out_of_space.txt', 'r') as f:
    text=f.read()
vocab = set(tokenize_text(text))
vocab_to_int = {c: i for i, c in enumerate(vocab)}
int_to_vocab = dict(enumerate(vocab))
encoded = np.array([vocab_to_int[c] for c in tokenize_text(text)], dtype=np.int32)

Let's check out the first 100 characters, make sure everything is peachy.  line of a book ever.

In [53]:
text[:100]

'THE COLOUR OUT OF SPACE\n\nWest of Arkham the hills rise wild, and there are valleys with deep woods t'

And we can see the characters encoded as integers.

In [54]:
encoded[:100]

array([3165, 2526, 4555, 2526, 2082, 2526, 1667, 2526, 3059, 4547, 4547,
        934, 2526,  526, 2526, 1735, 2526, 2827, 2526, 1253, 2526, 1170,
       2526, 1094,  518, 2526, 4519, 2526, 2602, 2526, 3480, 2526,  251,
       2526, 3356, 2526, 1803, 2526,   35, 2526, 2150, 2526, 4611, 2526,
       2914, 2526,  987, 2526, 3402, 2526, 1258, 1002, 2526, 2859, 2526,
       3480, 2526, 4589, 2526, 4005, 2526, 4097, 2526,  931, 2526, 2827,
       2526,  717, 2526, 2222, 2526, 4064,  518, 2526, 4519, 2526,  931,
       2526, 4819, 2526, 2413, 2526, 1633, 2526, 1150, 2526, 3402, 2526,
       2568, 2526, 4702, 2526, 2827, 2526, 2109, 2526,  526, 2526,  233,
       1002], dtype=int32)

Since the network is working with individual english tokens, it's similar to a classification problem in which we are trying to predict the next character from the previous text.  Here's how many 'classes' our network has to pick from.

In [55]:
len(vocab)

4978

## Making training mini-batches

Here is where we'll make our mini-batches for training. Remember that we want our batches to be multiple sequences of some desired number of sequence steps. Considering a simple example, our batches would look like this:

<img src="assets/sequence_batching@1x.png" width=500px>


<br>
We have our text encoded as integers as one long array in `encoded`. Let's create a function that will give us an iterator for our batches. I like using [generator functions](https://jeffknupp.com/blog/2013/04/07/improve-your-python-yield-and-generators-explained/) to do this. Then we can pass `encoded` into this function and get our batch generator.

The first thing we need to do is discard some of the text so we only have completely full batches. Each batch contains $N \times M$ characters, where $N$ is the batch size (the number of sequences) and $M$ is the number of steps. Then, to get the number of batches we can make from some array `arr`, you divide the length of `arr` by the batch size. Once you know the number of batches and the batch size, you can get the total number of characters to keep.

After that, we need to split `arr` into $N$ sequences. You can do this using `arr.reshape(size)` where `size` is a tuple containing the dimensions sizes of the reshaped array. We know we want $N$ sequences (`n_seqs` below), let's make that the size of the first dimension. For the second dimension, you can use `-1` as a placeholder in the size, it'll fill up the array with the appropriate data for you. After this, you should have an array that is $N \times (M * K)$ where $K$ is the number of batches.

Now that we have this array, we can iterate through it to get our batches. The idea is each batch is a $N \times M$ window on the array. For each subsequent batch, the window moves over by `n_steps`. We also want to create both the input and target arrays. Remember that the targets are the inputs shifted over one character. You'll usually see the first input character used as the last target character, so something like this:
```python
y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
```
where `x` is the input batch and `y` is the target batch.

The way I like to do this window is use `range` to take steps of size `n_steps` from $0$ to `arr.shape[1]`, the total number of steps in each sequence. That way, the integers you get from `range` always point to the start of a batch, and each window is `n_steps` wide.

In [56]:
def get_batches(arr, n_seqs, n_steps):
    '''Create a generator that returns batches of size
       n_seqs x n_steps from arr.
       
       Arguments
       ---------
       arr: Array you want to make batches from
       n_seqs: Batch size, the number of sequences per batch
       n_steps: Number of sequence steps per batch
    '''
    # Get the batch size and number of batches we can make
    batch_size = n_seqs * n_steps 
    n_batches =  len(arr)//batch_size
    
    # Keep only enough characters to make full batches
    arr =  arr[:n_batches*batch_size]
    
    # Reshape into n_seqs rows
    arr = arr.reshape((n_seqs,-1))
    
    for n in range(0, arr.shape[1], n_steps):
        # The features
        x = arr[:,n:n+n_steps]
        # The targets, shifted by one
        y = np.zeros(x.shape)
        y[:,:-1],y[:,-1] = x[:,1:] ,x[:,0]
        yield x, y

Now I'll make my data sets and we can check out what's going on here. Here I'm going to use a batch size of 10 and 50 sequence steps.

In [57]:
batches = get_batches(encoded, 10, 50)
x, y = next(batches)

In [58]:
print('x\n', x[:10, :10])
print('\ny\n', y[:10, :10])

x
 [[3165 2526 4555 2526 2082 2526 1667 2526 3059 4547]
 [2526  151 2526 1165 2526  437 2526  816  518 2526]
 [2526 2549 2526 3992  518 2526 4519 2526  687 2526]
 [2367 2526 3713 2526 4904 2526 2112 2526  808 2526]
 [1319 2526 4392 2526 3705 2526  120 2526 2256 2526]
 [2827 2526 4969 1134 2526  909 2526  526 2526 2827]
 [2526 2821 2526 2827 2526 1146 2526  526 2526 3596]
 [3903 2526  333 2526 4293 1139 2526 4519 2526 1906]
 [2526  283 2526 2827 2526 4700 2526   90 2526 2935]
 [2526   90 2526 2851 2526 2880 2526  272 2526 4519]]

y
 [[ 2526.  4555.  2526.  2082.  2526.  1667.  2526.  3059.  4547.  4547.]
 [  151.  2526.  1165.  2526.   437.  2526.   816.   518.  2526.  4519.]
 [ 2549.  2526.  3992.   518.  2526.  4519.  2526.   687.  2526.  2060.]
 [ 2526.  3713.  2526.  4904.  2526.  2112.  2526.   808.  2526.  2827.]
 [ 2526.  4392.  2526.  3705.  2526.   120.  2526.  2256.  2526.   526.]
 [ 2526.  4969.  1134.  2526.   909.  2526.   526.  2526.  2827.  2526.]
 [ 2821.  2526.  2827.  

## Building the model

Below is where you'll build the network. We'll break it up into parts so it's easier to reason about each bit. Then we can connect them up into the whole network.

<img src="assets/charRNN.png" width=500px>


### Inputs

First off we'll create our input placeholders. As usual we need placeholders for the training data and the targets. We'll also create a placeholder for dropout layers called `keep_prob`. This will be a scalar, that is a 0-D tensor. To make a scalar, you create a placeholder without giving it a size.

In [59]:
def build_inputs(batch_size, num_steps):
    ''' Define placeholders for inputs, targets, and dropout 
    
        Arguments
        ---------
        batch_size: Batch size, number of sequences per batch
        num_steps: Number of sequence steps in a batch
        
    '''
    # Declare placeholders we'll feed into the graph
    inputs = tf.placeholder(tf.int32,[batch_size,num_steps],name="inputs")
    targets = tf.placeholder(tf.int32,[batch_size,num_steps],name="targets")
    
    # Keep probability placeholder for drop out layers
    keep_prob = tf.placeholder(tf.float32,name="keep_prob")
    
    return inputs, targets, keep_prob

### LSTM Cell

Here we will create the LSTM cell we'll use in the hidden layer. We'll use this cell as a building block for the RNN. So we aren't actually defining the RNN here, just the type of cell we'll use in the hidden layer.

We first create a basic LSTM cell with

```python
lstm = tf.contrib.rnn.BasicLSTMCell(num_units)
```

where `num_units` is the number of units in the hidden layers in the cell. Then we can add dropout by wrapping it with 

```python
tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
```
You pass in a cell and it will automatically add dropout to the inputs or outputs. Finally, we can stack up the LSTM cells into layers with [`tf.contrib.rnn.MultiRNNCell`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/contrib/rnn/MultiRNNCell). With this, you pass in a list of cells and it will send the output of one cell into the next cell. For example,

```python
tf.contrib.rnn.MultiRNNCell([cell]*num_layers)
```

This might look a little weird if you know Python well because this will create a list of the same `cell` object. However, TensorFlow will create different weight matrices for all `cell` objects. Even though this is actually multiple LSTM cells stacked on each other, you can treat the multiple layers as one cell.

We also need to create an initial cell state of all zeros. This can be done like so

```python
initial_state = cell.zero_state(batch_size, tf.float32)
```


In [60]:
def build_lstm(lstm_size, num_layers, batch_size, keep_prob):
    ''' Build LSTM cell.
    
        Arguments
        ---------
        keep_prob: Scalar tensor (tf.placeholder) for the dropout keep probability
        lstm_size: Size of the hidden layers in the LSTM cells
        num_layers: Number of LSTM layers
        batch_size: Batch size

    '''
    ### Build the LSTM Cell
    # Use a basic LSTM cell
    # Add dropout to the cell outputs
    # Stack up multiple LSTM layers, for deep learning
    cell = tf.contrib.rnn.MultiRNNCell([tf.contrib.rnn.DropoutWrapper( tf.contrib.rnn.BasicLSTMCell(lstm_size)) for _ in range(num_layers)])
    initial_state = cell.zero_state(batch_size,tf.float32)
    
    return cell, initial_state

### RNN Output

Here we'll create the output layer. We need to connect the output of the RNN cells to a full connected layer with a softmax output. The softmax output gives us a probability distribution we can use to predict the next character, so we want this layer to have size $C$, the number of classes/characters we have in our text.

If our input has batch size $N$, number of steps $M$, and the hidden layer has $L$ hidden units, then the output is a 3D tensor with size $N \times M \times L$. The output of each LSTM cell has size $L$, we have $M$ of them, one for each sequence step, and we have $N$ sequences. So the total size is $N \times M \times L$. 

We are using the same fully connected layer, the same weights, for each of the outputs. Then, to make things easier, we should reshape the outputs into a 2D tensor with shape $(M * N) \times L$. That is, one row for each sequence and step, where the values of each row are the output from the LSTM cells. We get the LSTM output as a list, `lstm_output`. First we need to concatenate this whole list into one array with [`tf.concat`](https://www.tensorflow.org/api_docs/python/tf/concat). Then, reshape it (with `tf.reshape`) to size $(M * N) \times L$.

One we have the outputs reshaped, we can do the matrix multiplication with the weights. We need to wrap the weight and bias variables in a variable scope with `tf.variable_scope(scope_name)` because there are weights being created in the LSTM cells. TensorFlow will throw an error if the weights created here have the same names as the weights created in the LSTM cells, which they will be default. To avoid this, we wrap the variables in a variable scope so we can give them unique names.


In [61]:
def build_output(lstm_output, in_size, out_size):
    ''' Build a softmax layer, return the softmax output and logits.
    
        Arguments
        ---------
        
        lstm_output: List of output tensors from the LSTM layer
        in_size: Size of the input tensor, for example, size of the LSTM cells
        out_size: Size of this softmax layer
    
    '''

    # Reshape output so it's a bunch of rows, one row for each step for each sequence.
    # Concatenate lstm_output over axis 1 (the columns)
    seq_output = tf.concat(lstm_output,axis=1)
    # Reshape seq_output to a 2D tensor with lstm_size columns
    x = tf.reshape(seq_output,[-1,in_size])
    
    # Connect the RNN outputs to a softmax layer
    with tf.variable_scope('softmax'):
        # Create the weight and bias variables here
        softmax_w = tf.Variable(tf.truncated_normal((in_size, out_size),stddev=0.1))
        softmax_b = tf.Variable(tf.zeros([out_size]))
    
    # Since output is a bunch of rows of RNN cell outputs, logits will be a bunch
    # of rows of logit outputs, one for each step and sequence
    logits =  tf.add(tf.matmul(x,softmax_w),softmax_b) 
    
    # Use softmax to get the probabilities for predicted characters
    out = tf.nn.softmax(logits,name ="out")
    
    return out, logits

### Training loss

Next up is the training loss. We get the logits and targets and calculate the softmax cross-entropy loss. First we need to one-hot encode the targets, we're getting them as encoded characters. Then, reshape the one-hot targets so it's a 2D tensor with size $(M*N) \times C$ where $C$ is the number of classes/characters we have. Remember that we reshaped the LSTM outputs and ran them through a fully connected layer with $C$ units. So our logits will also have size $(M*N) \times C$.

Then we run the logits and targets through `tf.nn.softmax_cross_entropy_with_logits` and find the mean to get the loss.

In [62]:
def build_loss(logits, targets, lstm_size, num_classes):
    ''' Calculate the loss from the logits and the targets.
    
        Arguments
        ---------
        logits: Logits from final fully connected layer
        targets: Targets for supervised learning
        lstm_size: Number of LSTM hidden units
        num_classes: Number of classes in targets
        
    '''
    # One-hot encode targets and reshape to match logits, one row per sequence per step
    y_one_hot = tf.one_hot(targets,num_classes)
    y_reshaped =  tf.reshape(y_one_hot,logits.get_shape())
    
    # Softmax cross entropy loss
    loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits,labels=y_reshaped))
    
    return loss

### Optimizer

Here we build the optimizer. Normal RNNs have have issues gradients exploding and disappearing. LSTMs fix the disappearance problem, but the gradients can still grow without bound. To fix this, we can clip the gradients above some threshold. That is, if a gradient is larger than that threshold, we set it to the threshold. This will ensure the gradients never grow overly large. Then we use an AdamOptimizer for the learning step.

In [63]:
def build_optimizer(loss, learning_rate, grad_clip):
    ''' Build optmizer for training, using gradient clipping.
    
        Arguments:
        loss: Network loss
        learning_rate: Learning rate for optimizer
    
    '''
    
    # Optimizer for training, using gradient clipping to control exploding gradients
    tvars = tf.trainable_variables()
    grads, _ = tf.clip_by_global_norm(tf.gradients(loss, tvars), grad_clip)
    train_op = tf.train.AdamOptimizer(learning_rate)
    optimizer = train_op.apply_gradients(zip(grads, tvars))
    
    return optimizer

### Build the network

Now we can put all the pieces together and build a class for the network. To actually run data through the LSTM cells, we will use [`tf.nn.dynamic_rnn`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/nn/dynamic_rnn). This function will pass the hidden and cell states across LSTM cells appropriately for us. It returns the outputs for each LSTM cell at each step for each sequence in the mini-batch. It also gives us the final LSTM state. We want to save this state as `final_state` so we can pass it to the first LSTM cell in the the next mini-batch run. For `tf.nn.dynamic_rnn`, we pass in the cell and initial state we get from `build_lstm`, as well as our input sequences. Also, we need to one-hot encode the inputs before going into the RNN. 


In [64]:
class CharRNN:
    
    def __init__(self, num_classes, batch_size=64, num_steps=50, 
                       lstm_size=128, num_layers=2, learning_rate=0.001, 
                       grad_clip=5, sampling=False):
    
        # When we're using this network for sampling later, we'll be passing in
        # one character at a time, so providing an option for that
        if sampling == True:
            batch_size, num_steps = 1, 1
        else:
            batch_size, num_steps = batch_size, num_steps

        tf.reset_default_graph()
        
        # Build the input placeholder tensors
        self.inputs, self.targets, self.keep_prob = build_inputs(batch_size,num_steps)
        # Build the LSTM cell
        cell, self.initial_state = build_lstm(lstm_size,num_layers,batch_size,self.keep_prob)
        ### Run the data through the RNN layers
        # First, one-hot encode the input tokens
        x_one_hot = tf.one_hot(self.inputs,num_classes)
        
        # Run each sequence step through the RNN with tf.nn.dynamic_rnn 
        outputs, state = tf.nn.dynamic_rnn(cell,x_one_hot,initial_state=self.initial_state)
        self.final_state = state
        
        # Get softmax predictions and logits
        self.prediction, self.logits = build_output(outputs,lstm_size,num_classes)
        
        # Loss and optimizer (with gradient clipping)
        self.loss =  build_loss(self.logits,self.targets,lstm_size,num_classes)
        self.optimizer = build_optimizer(self.loss,learning_rate,grad_clip)

## Hyperparameters

Here are the hyperparameters for the network.

* `batch_size` - Number of sequences running through the network in one pass.
* `num_steps` - Number of characters in the sequence the network is trained on. Larger is better typically, the network will learn more long range dependencies. But it takes longer to train. 100 is typically a good number here.
* `lstm_size` - The number of units in the hidden layers.
* `num_layers` - Number of hidden LSTM layers to use
* `learning_rate` - Learning rate for training
* `keep_prob` - The dropout keep probability when training. If you're network is overfitting, try decreasing this.

Here's some good advice from Andrej Karpathy on training the network:. 

> ## Tips and Tricks

>### Monitoring Validation Loss vs. Training Loss
>If you're somewhat new to Machine Learning or Neural Networks it can take a bit of expertise to get good models. The most important quantity to keep track of is the difference between your training loss (printed during training) and the validation loss (printed once in a while when the RNN is run on the validation data (by default every 1000 iterations)). In particular:

> - If your training loss is much lower than validation loss then this means the network might be **overfitting**. Solutions to this are to decrease your network size, or to increase dropout. For example you could try dropout of 0.5 and so on.
> - If your training/validation loss are about equal then your model is **underfitting**. Increase the size of your model (either number of layers or the raw number of neurons per layer)

> ### Approximate number of parameters

> The two most important parameters that control the model are `lstm_size` and `num_layers`. I would advise that you always use `num_layers` of either 2/3. The `lstm_size` can be adjusted based on how much data you have. The two important quantities to keep track of here are:

> - The number of parameters in your model. This is printed when you start training.
> - The size of your dataset. 1MB file is approximately 1 million characters.

>These two should be about the same order of magnitude. It's a little tricky to tell. Here are some examples:

> - I have a 100MB dataset and I'm using the default parameter settings (which currently print 150K parameters). My data size is significantly larger (100 mil >> 0.15 mil), so I expect to heavily underfit. I am thinking I can comfortably afford to make `lstm_size` larger.
> - I have a 10MB dataset and running a 10 million parameter model. I'm slightly nervous and I'm carefully monitoring my validation loss. If it's larger than my training loss then I may want to try to increase dropout a bit and see if that helps the validation loss.

> ### Best models strategy

>The winning strategy to obtaining very good models (if you have the compute time) is to always err on making the network larger (as large as you're willing to wait for it to compute) and then try different dropout values (between 0,1). Whatever model has the best validation performance (the loss, written in the checkpoint filename, low is good) is the one you should use in the end.

>It is very common in deep learning to run many different models with many different hyperparameter settings, and in the end take whatever checkpoint gave the best validation performance.

>By the way, the size of your training and validation splits are also parameters. Make sure you have a decent amount of data in your validation set or otherwise the validation performance will be noisy and not very informative.

In [65]:
batch_size = 50         # Sequences per batch
num_steps = 50          # Number of sequence steps per batch
lstm_size = 600         # Size of hidden layers in LSTMs
num_layers = 2          # Number of LSTM layers
learning_rate = 0.001    # Learning rate
keep_prob = 0.20         # Dropout keep probability

## Time for training

This is typical training code, passing inputs and targets into the network, then running the optimizer. Here we also get back the final LSTM state for the mini-batch. Then, we pass that state back into the network so the next batch can continue the state from the previous batch. And every so often (set by `save_every_n`) I save a checkpoint.

Here I'm saving checkpoints with the format

`i{iteration number}_l{# hidden layer units}.ckpt`


In [66]:
epochs = 1200
# Save every N iterations
save_every_n = 300
print_loss_every_n = 50
with tf.device("/gpu:0"):
    model = CharRNN(len(vocab), batch_size=batch_size, num_steps=num_steps,
                lstm_size=lstm_size, num_layers=num_layers, 
                learning_rate=learning_rate)
    print("after model")

saver = tf.train.Saver(max_to_keep=100)
print("after saver")
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print("after initializer")
    # Use the line below to load a checkpoint and resume training
    #saver.restore(sess, 'checkpoints/______.ckpt')
    counter = 0
    for e in range(epochs):
        # Train network
        
        new_state = sess.run(model.initial_state)
        loss = 0
        for x, y in get_batches(encoded, batch_size, num_steps):
            
            
            start = time.time()
            feed = {model.inputs: x,
                    model.targets: y,
                    model.keep_prob: keep_prob,
                    model.initial_state: new_state}
            batch_loss, new_state, _ = sess.run([model.loss, 
                                                 model.final_state, 
                                                 model.optimizer], 
                                                 feed_dict=feed)
            
            end = time.time()
            if counter%print_loss_every_n == 0:
                print('Epoch: {}/{}... '.format(e+1, epochs),
                      'Training Step: {}... '.format(counter),
                      'Training loss: {:.4f}... '.format(batch_loss),
                      '{:.4f} sec/batch'.format((end-start)))
        
            if (counter % save_every_n == 0):
                saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))
            counter += 1
    
    saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))

after model
after saver
after initializer
Epoch: 1/1200...  Training Step: 0...  Training loss: 8.5115...  0.3660 sec/batch
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'dict' object has no attribute 'name'
Epoch: 3/1200...  Training Step: 50...  Training loss: 4.1147...  0.2502 sec/batch
Epoch: 6/1200...  Training Step: 100...  Training loss: 3.7786...  0.2478 sec/batch
Epoch: 8/1200...  Training Step: 150...  Training loss: 3.3914...  0.2480 sec/batch
Epoch: 11/1200...  Training Step: 200...  Training loss: 3.4471...  0.2480 sec/batch
Epoch: 13/1200...  Training Step: 250...  Training loss: 3.2191...  0.2502 sec/batch
Epoch: 16/1200...  Training Step: 300...  Training loss: 3.2668...  0.2578 sec/batch
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'dict' object has no attribute 'name'
Epoch: 18/1200...  Training Step: 350...  Training loss: 2.9438...  0.2493 sec/batch
Epoch: 21/1200...  Training Step:

Epoch: 171/1200...  Training Step: 3400...  Training loss: 0.0453...  0.2555 sec/batch
Epoch: 173/1200...  Training Step: 3450...  Training loss: 0.0106...  0.2541 sec/batch
Epoch: 176/1200...  Training Step: 3500...  Training loss: 0.0494...  0.2597 sec/batch
Epoch: 178/1200...  Training Step: 3550...  Training loss: 0.0083...  0.2495 sec/batch
Epoch: 181/1200...  Training Step: 3600...  Training loss: 0.0439...  0.2499 sec/batch
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'dict' object has no attribute 'name'
Epoch: 183/1200...  Training Step: 3650...  Training loss: 0.0044...  0.2515 sec/batch
Epoch: 186/1200...  Training Step: 3700...  Training loss: 0.0425...  0.2505 sec/batch
Epoch: 188/1200...  Training Step: 3750...  Training loss: 0.0036...  0.2511 sec/batch
Epoch: 191/1200...  Training Step: 3800...  Training loss: 0.0419...  0.2711 sec/batch
Epoch: 193/1200...  Training Step: 3850...  Training loss: 0.0028...  0.2677 sec/batch
Epoc

Epoch: 346/1200...  Training Step: 6900...  Training loss: 0.0380...  0.2477 sec/batch
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'dict' object has no attribute 'name'
Epoch: 348/1200...  Training Step: 6950...  Training loss: 0.0011...  0.2512 sec/batch
Epoch: 351/1200...  Training Step: 7000...  Training loss: 0.0381...  0.2507 sec/batch
Epoch: 353/1200...  Training Step: 7050...  Training loss: 0.0011...  0.2507 sec/batch
Epoch: 356/1200...  Training Step: 7100...  Training loss: 0.0379...  0.2502 sec/batch
Epoch: 358/1200...  Training Step: 7150...  Training loss: 0.0010...  0.2513 sec/batch
Epoch: 361/1200...  Training Step: 7200...  Training loss: 0.0379...  0.2497 sec/batch
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'dict' object has no attribute 'name'
Epoch: 363/1200...  Training Step: 7250...  Training loss: 0.0011...  0.2491 sec/batch
Epoch: 366/1200...  Training Step: 7300...  Training

Epoch: 513/1200...  Training Step: 10250...  Training loss: 0.0007...  0.2485 sec/batch
Epoch: 516/1200...  Training Step: 10300...  Training loss: 0.0374...  0.2512 sec/batch
Epoch: 518/1200...  Training Step: 10350...  Training loss: 0.0008...  0.2503 sec/batch
Epoch: 521/1200...  Training Step: 10400...  Training loss: 0.0375...  0.2493 sec/batch
Epoch: 523/1200...  Training Step: 10450...  Training loss: 0.0007...  0.2505 sec/batch
Epoch: 526/1200...  Training Step: 10500...  Training loss: 0.0375...  0.2490 sec/batch
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'dict' object has no attribute 'name'
Epoch: 528/1200...  Training Step: 10550...  Training loss: 0.0011...  0.2493 sec/batch
Epoch: 531/1200...  Training Step: 10600...  Training loss: 0.0374...  0.2495 sec/batch
Epoch: 533/1200...  Training Step: 10650...  Training loss: 0.0019...  0.2498 sec/batch
Epoch: 536/1200...  Training Step: 10700...  Training loss: 0.0375...  0.2487 sec/

Epoch: 686/1200...  Training Step: 13700...  Training loss: 0.0372...  0.2509 sec/batch
Epoch: 688/1200...  Training Step: 13750...  Training loss: 0.0002...  0.2497 sec/batch
Epoch: 691/1200...  Training Step: 13800...  Training loss: 0.0372...  0.2503 sec/batch
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'dict' object has no attribute 'name'
Epoch: 693/1200...  Training Step: 13850...  Training loss: 0.0001...  0.2498 sec/batch
Epoch: 696/1200...  Training Step: 13900...  Training loss: 0.0373...  0.2490 sec/batch
Epoch: 698/1200...  Training Step: 13950...  Training loss: 0.0001...  0.2514 sec/batch
Epoch: 701/1200...  Training Step: 14000...  Training loss: 0.0374...  0.2516 sec/batch
Epoch: 703/1200...  Training Step: 14050...  Training loss: 0.0001...  0.2508 sec/batch
Epoch: 706/1200...  Training Step: 14100...  Training loss: 0.0374...  0.2489 sec/batch
Type is unsupported, or the types of the items don't match field type in Collectio

Type is unsupported, or the types of the items don't match field type in CollectionDef.
'dict' object has no attribute 'name'
Epoch: 858/1200...  Training Step: 17150...  Training loss: 0.0000...  0.2535 sec/batch
Epoch: 861/1200...  Training Step: 17200...  Training loss: 0.0374...  0.2510 sec/batch
Epoch: 863/1200...  Training Step: 17250...  Training loss: 0.0000...  0.2504 sec/batch
Epoch: 866/1200...  Training Step: 17300...  Training loss: 0.0373...  0.2486 sec/batch
Epoch: 868/1200...  Training Step: 17350...  Training loss: 0.0000...  0.2494 sec/batch
Epoch: 871/1200...  Training Step: 17400...  Training loss: 0.0375...  0.2504 sec/batch
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'dict' object has no attribute 'name'
Epoch: 873/1200...  Training Step: 17450...  Training loss: 0.0000...  0.2505 sec/batch
Epoch: 876/1200...  Training Step: 17500...  Training loss: 0.0373...  0.2506 sec/batch
Epoch: 878/1200...  Training Step: 17550... 

Epoch: 1026/1200...  Training Step: 20500...  Training loss: 0.0372...  0.2496 sec/batch
Epoch: 1028/1200...  Training Step: 20550...  Training loss: 0.0000...  0.2494 sec/batch
Epoch: 1031/1200...  Training Step: 20600...  Training loss: 0.0374...  0.2491 sec/batch
Epoch: 1033/1200...  Training Step: 20650...  Training loss: 0.0000...  0.2486 sec/batch
Epoch: 1036/1200...  Training Step: 20700...  Training loss: 0.0372...  0.2504 sec/batch


ResourceExhaustedError: checkpoints/i20700_l600.ckpt.data-00000-of-00001.tempstate760644016919922100
	 [[Node: save/SaveV2 = SaveV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, beta1_power/_41, beta2_power/_43, rnn/multi_rnn_cell/cell_0/basic_lstm_cell/biases/_45, rnn/multi_rnn_cell/cell_0/basic_lstm_cell/biases/Adam/_47, rnn/multi_rnn_cell/cell_0/basic_lstm_cell/biases/Adam_1/_49, rnn/multi_rnn_cell/cell_0/basic_lstm_cell/weights/_51, rnn/multi_rnn_cell/cell_0/basic_lstm_cell/weights/Adam/_53, rnn/multi_rnn_cell/cell_0/basic_lstm_cell/weights/Adam_1/_55, rnn/multi_rnn_cell/cell_1/basic_lstm_cell/biases/_57, rnn/multi_rnn_cell/cell_1/basic_lstm_cell/biases/Adam/_59, rnn/multi_rnn_cell/cell_1/basic_lstm_cell/biases/Adam_1/_61, rnn/multi_rnn_cell/cell_1/basic_lstm_cell/weights/_63, rnn/multi_rnn_cell/cell_1/basic_lstm_cell/weights/Adam/_65, rnn/multi_rnn_cell/cell_1/basic_lstm_cell/weights/Adam_1/_67, softmax/Variable/_69, softmax/Variable/Adam/_71, softmax/Variable/Adam_1/_73, softmax/Variable_1/_75, softmax/Variable_1/Adam/_77, softmax/Variable_1/Adam_1/_79)]]

Caused by op 'save/SaveV2', defined at:
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/site-packages/tornado/ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-66-12e0f7862491>", line 11, in <module>
    saver = tf.train.Saver(max_to_keep=100)
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1139, in __init__
    self.build()
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1170, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 689, in build
    save_tensor = self._AddSaveOps(filename_tensor, saveables)
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 276, in _AddSaveOps
    save = self.save_op(filename_tensor, saveables)
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 219, in save_op
    tensors)
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 795, in save_v2
    tensors=tensors, name=name)
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2500, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/luis/anaconda2/envs/dlnd_gpu/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

ResourceExhaustedError (see above for traceback): checkpoints/i20700_l600.ckpt.data-00000-of-00001.tempstate760644016919922100
	 [[Node: save/SaveV2 = SaveV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, beta1_power/_41, beta2_power/_43, rnn/multi_rnn_cell/cell_0/basic_lstm_cell/biases/_45, rnn/multi_rnn_cell/cell_0/basic_lstm_cell/biases/Adam/_47, rnn/multi_rnn_cell/cell_0/basic_lstm_cell/biases/Adam_1/_49, rnn/multi_rnn_cell/cell_0/basic_lstm_cell/weights/_51, rnn/multi_rnn_cell/cell_0/basic_lstm_cell/weights/Adam/_53, rnn/multi_rnn_cell/cell_0/basic_lstm_cell/weights/Adam_1/_55, rnn/multi_rnn_cell/cell_1/basic_lstm_cell/biases/_57, rnn/multi_rnn_cell/cell_1/basic_lstm_cell/biases/Adam/_59, rnn/multi_rnn_cell/cell_1/basic_lstm_cell/biases/Adam_1/_61, rnn/multi_rnn_cell/cell_1/basic_lstm_cell/weights/_63, rnn/multi_rnn_cell/cell_1/basic_lstm_cell/weights/Adam/_65, rnn/multi_rnn_cell/cell_1/basic_lstm_cell/weights/Adam_1/_67, softmax/Variable/_69, softmax/Variable/Adam/_71, softmax/Variable/Adam_1/_73, softmax/Variable_1/_75, softmax/Variable_1/Adam/_77, softmax/Variable_1/Adam_1/_79)]]


#### Saved checkpoints

Read up on saving and loading checkpoints here: https://www.tensorflow.org/programmers_guide/variables

In [67]:
tf.train.get_checkpoint_state('checkpoints')

model_checkpoint_path: "checkpoints/i20400_l600.ckpt"
all_model_checkpoint_paths: "checkpoints/i0_l600.ckpt"
all_model_checkpoint_paths: "checkpoints/i300_l600.ckpt"
all_model_checkpoint_paths: "checkpoints/i600_l600.ckpt"
all_model_checkpoint_paths: "checkpoints/i900_l600.ckpt"
all_model_checkpoint_paths: "checkpoints/i1200_l600.ckpt"
all_model_checkpoint_paths: "checkpoints/i1500_l600.ckpt"
all_model_checkpoint_paths: "checkpoints/i1800_l600.ckpt"
all_model_checkpoint_paths: "checkpoints/i2100_l600.ckpt"
all_model_checkpoint_paths: "checkpoints/i2400_l600.ckpt"
all_model_checkpoint_paths: "checkpoints/i2700_l600.ckpt"
all_model_checkpoint_paths: "checkpoints/i3000_l600.ckpt"
all_model_checkpoint_paths: "checkpoints/i3300_l600.ckpt"
all_model_checkpoint_paths: "checkpoints/i3600_l600.ckpt"
all_model_checkpoint_paths: "checkpoints/i3900_l600.ckpt"
all_model_checkpoint_paths: "checkpoints/i4200_l600.ckpt"
all_model_checkpoint_paths: "checkpoints/i4500_l600.ckpt"
all_model_checkpoint_pat

## Sampling

Now that the network is trained, we'll can use it to generate new text. The idea is that we pass in a character, then the network will predict the next character. We can use the new one, to predict the next one. And we keep doing this to generate all new text. I also included some functionality to prime the network with some text by passing in a string and building up a state from that.

The network gives us predictions for each character. To reduce noise and make things a little less random, I'm going to only choose a new character from the top N most likely characters.



In [68]:
def pick_top_n(preds, vocab_size, top_n=5):
    p = np.squeeze(preds)
    p[np.argsort(p)[:-top_n]] = 0
    p = p / np.sum(p)
    c = np.random.choice(vocab_size, 1, p=p)[0]
    return c

In [69]:
def sample(checkpoint, n_samples, lstm_size, vocab_size, prime="The "):
    samples = tokenize_text(prime)
    model = CharRNN(len(vocab), lstm_size=lstm_size, sampling=True)
    saver = tf.train.Saver()
    with tf.Session() as sess:
        saver.restore(sess, checkpoint)
        new_state = sess.run(model.initial_state)
        for c in tokenize_text(prime):
            x = np.zeros((1, 1))
            x[0,0] = vocab_to_int[c]
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

        c = pick_top_n(preds, len(vocab))
        samples.append(int_to_vocab[c])

        for i in range(n_samples):
            x[0,0] = c
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

            c = pick_top_n(preds, len(vocab))
            samples.append(int_to_vocab[c])
        
    return ''.join(samples).replace("new_line_token","\n")

Here, pass in the path to a checkpoint and sample from the network.

In [70]:
tf.train.latest_checkpoint('checkpoints')

'checkpoints/i20400_l600.ckpt'

## Generate new text from "base" text

In [ ]:
text_to_try = ["horror","night","dream","thing","That night","mountain","Ammi","Cthulhu"]

In [71]:
checkpoint = tf.train.latest_checkpoint('checkpoints')

for text in text_to_try:
    print("------------------------",text)
    samp = sample(checkpoint, 200, lstm_size, len(vocab), prime=text)
    print(samp)
    print("------------------------")

------------------------ horror
INFO:tensorflow:Restoring parameters from checkpoints/i20400_l600.ckpt
horror and called them gods, monsters, mythical beings of all sorts and kinds...

--Algernon Blackwood

I. The Horror In Clay

The most merciful thing in the world, I think, is the inability of the human mind to correlate all its contents. We live on a   near the well was a vacant space, except where the earth had caved in; and whereas it had been a good seven feet across the day before, it was now scarcely five. It was still hot, and the sages studied its surface curiously as they detached another  
------------------------
------------------------ night
INFO:tensorflow:Restoring parameters from checkpoints/i20400_l600.ckpt
night the while the shaft of phosphorescence from the well was getting brighter and brighter, bringing to the minds of the huddled men, a sense of doom and abnormality which far outraced any image their conscious minds could form. It was no longer shining out; it 