# Recurrent neural networks for text generation

In this notebook, we will build a character-wise RNN trained on Anna Karenina. It'll be able to generate new text based on the text from the book.

This network is based off of Andrej Karpathy's [post on RNNs](http://karpathy.github.io/2015/05/21/rnn-effectiveness/) and [implementation in Torch](https://github.com/karpathy/char-rnn). Also, some information [here at r2rt](http://r2rt.com/recurrent-neural-networks-in-tensorflow-ii.html) and from [Sherjil Ozair](https://github.com/sherjilozair/char-rnn-tensorflow) on GitHub. Below is the general architecture of the character-wise RNN.

<img src="assets/charseq.jpeg" width="500">

In [1]:
import time
from collections import namedtuple

import numpy as np
import tensorflow as tf

First we'll load the text file and convert it into integers for our network to use. Here I'm creating a couple dictionaries to convert the characters to and from integers. Encoding the characters as integers makes it easier to use as input in the network.

In [2]:
with open('anna.txt', 'r') as f:
    text=f.read()
vocab = set(text)
vocab_to_int = {c: i for i, c in enumerate(vocab)}
int_to_vocab = dict(enumerate(vocab))
encoded = np.array([vocab_to_int[c] for c in text], dtype=np.int32)

Let's check out the first 100 characters, make sure everything is peachy. According to the [American Book Review](http://americanbookreview.org/100bestlines.asp), this is the 6th best first line of a book ever.

In [3]:
text[:100]

'Chapter 1\n\n\nHappy families are all alike; every unhappy family is unhappy in its own\nway.\n\nEverythin'

And we can see the characters encoded as integers.

In [4]:
encoded[:100]

array([67, 31, 30, 44, 28, 64, 26, 22, 60,  0,  0,  0, 58, 30, 44, 44, 63,
       22, 82, 30, 59, 66, 19, 66, 64, 80, 22, 30, 26, 64, 22, 30, 19, 19,
       22, 30, 19, 66, 76, 64, 57, 22, 64, 78, 64, 26, 63, 22, 51, 41, 31,
       30, 44, 44, 63, 22, 82, 30, 59, 66, 19, 63, 22, 66, 80, 22, 51, 41,
       31, 30, 44, 44, 63, 22, 66, 41, 22, 66, 28, 80, 22, 12, 43, 41,  0,
       43, 30, 63,  9,  0,  0, 71, 78, 64, 26, 63, 28, 31, 66, 41], dtype=int32)

Since the network is working with individual characters, it's similar to a classification problem in which we are trying to predict the next character from the previous text.  Here's how many 'classes' our network has to pick from.

In [5]:
len(vocab)

83

## Making training mini-batches

Here is where we'll make our mini-batches for training. Remember that we want our batches to be multiple sequences of some desired number of sequence steps. Considering a simple example, our batches would look like this:

<img src="assets/sequence_batching@1x.png" width=500px>


<br>
We have our text encoded as integers as one long array in `encoded`. Let's create a function that will give us an iterator for our batches. I like using [generator functions](https://jeffknupp.com/blog/2013/04/07/improve-your-python-yield-and-generators-explained/) to do this. Then we can pass `encoded` into this function and get our batch generator.

The first thing we need to do is discard some of the text so we only have completely full batches. Each batch contains $N \times M$ characters, where $N$ is the batch size (the number of sequences) and $M$ is the number of steps. Then, to get the number of batches we can make from some array `arr`, you divide the length of `arr` by the batch size. Once you know the number of batches and the batch size, you can get the total number of characters to keep.

After that, we need to split `arr` into $N$ sequences. You can do this using `arr.reshape(size)` where `size` is a tuple containing the dimensions sizes of the reshaped array. We know we want $N$ sequences (`n_seqs` below), let's make that the size of the first dimension. For the second dimension, you can use `-1` as a placeholder in the size, it'll fill up the array with the appropriate data for you. After this, you should have an array that is $N \times (M * K)$ where $K$ is the number of batches.

Now that we have this array, we can iterate through it to get our batches. The idea is each batch is a $N \times M$ window on the array. For each subsequent batch, the window moves over by `n_steps`. We also want to create both the input and target arrays. Remember that the targets are the inputs shifted over one character. You'll usually see the first input character used as the last target character, so something like this:
```python
y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
```
where `x` is the input batch and `y` is the target batch.

The way I like to do this window is use `range` to take steps of size `n_steps` from $0$ to `arr.shape[1]`, the total number of steps in each sequence. That way, the integers you get from `range` always point to the start of a batch, and each window is `n_steps` wide.

> **Exercise:** Write the code for creating batches in the function below. The exercises in this notebook _will not be easy_. I've provided a notebook with solutions alongside this notebook. If you get stuck, checkout the solutions. The most important thing is that you don't copy and paste the code into here, **type out the solution code yourself.**

In [6]:
def get_batches(arr, n_seqs, n_steps):
    '''Create a generator that returns batches of size
       n_seqs x n_steps from arr.
       
       Arguments
       ---------
       arr: Array you want to make batches from
       n_seqs: Batch size, the number of sequences per batch
       n_steps: Number of sequence steps per batch
    '''
    # Get the batch size and number of batches we can make
    batch_size = n_seqs * n_steps 
    n_batches =  len(arr)//batch_size
    
    # Keep only enough characters to make full batches
    arr =  arr[:n_batches*batch_size]
    
    # Reshape into n_seqs rows
    arr = arr.reshape((n_seqs,-1))
    
    for n in range(0, arr.shape[1], n_steps):
        # The features
        x = arr[:,n:n+n_steps]
        # The targets, shifted by one
        y = np.zeros(x.shape)
        y[:,:-1],y[:,-1] = x[:,1:] ,x[:,0]
        yield x, y

Now I'll make my data sets and we can check out what's going on here. Here I'm going to use a batch size of 10 and 50 sequence steps.

In [7]:
batches = get_batches(encoded, 10, 50)
x, y = next(batches)

In [8]:
print('x\n', x[:10, :10])
print('\ny\n', y[:10, :10])

x
 [[67 31 30 44 28 64 26 22 60  0]
 [22 30 59 22 41 12 28 22 68 12]
 [78 66 41  9  0  0  3 54 64 80]
 [41 22 10 51 26 66 41 68 22 31]
 [22 66 28 22 66 80 69 22 80 66]
 [22 32 28 22 43 30 80  0 12 41]
 [31 64 41 22 21 12 59 64 22 82]
 [57 22 49 51 28 22 41 12 43 22]
 [28 22 66 80 41 61 28  9 22 65]
 [22 80 30 66 10 22 28 12 22 31]]

y
 [[ 31.  30.  44.  28.  64.  26.  22.  60.   0.   0.]
 [ 30.  59.  22.  41.  12.  28.  22.  68.  12.  66.]
 [ 66.  41.   9.   0.   0.   3.  54.  64.  80.  69.]
 [ 22.  10.  51.  26.  66.  41.  68.  22.  31.  66.]
 [ 66.  28.  22.  66.  80.  69.  22.  80.  66.  26.]
 [ 32.  28.  22.  43.  30.  80.   0.  12.  41.  19.]
 [ 64.  41.  22.  21.  12.  59.  64.  22.  82.  12.]
 [ 22.  49.  51.  28.  22.  41.  12.  43.  22.  80.]
 [ 22.  66.  80.  41.  61.  28.   9.  22.  65.  31.]
 [ 80.  30.  66.  10.  22.  28.  12.  22.  31.  64.]]


In [9]:
x

array([[67, 31, 30, 44, 28, 64, 26, 22, 60,  0,  0,  0, 58, 30, 44, 44, 63,
        22, 82, 30, 59, 66, 19, 66, 64, 80, 22, 30, 26, 64, 22, 30, 19, 19,
        22, 30, 19, 66, 76, 64, 57, 22, 64, 78, 64, 26, 63, 22, 51, 41],
       [22, 30, 59, 22, 41, 12, 28, 22, 68, 12, 66, 41, 68, 22, 28, 12, 22,
        80, 28, 30, 63, 69,  3, 22, 30, 41, 80, 43, 64, 26, 64, 10, 22, 34,
        41, 41, 30, 69, 22, 80, 59, 66, 19, 66, 41, 68, 69, 22, 49, 51],
       [78, 66, 41,  9,  0,  0,  3, 54, 64, 80, 69, 22, 66, 28, 61, 80, 22,
        80, 64, 28, 28, 19, 64, 10,  9, 22, 65, 31, 64, 22, 44, 26, 66, 21,
        64, 22, 66, 80, 22, 59, 30, 68, 41, 66, 82, 66, 21, 64, 41, 28],
       [41, 22, 10, 51, 26, 66, 41, 68, 22, 31, 66, 80, 22, 21, 12, 41, 78,
        64, 26, 80, 30, 28, 66, 12, 41, 22, 43, 66, 28, 31, 22, 31, 66, 80,
         0, 49, 26, 12, 28, 31, 64, 26, 22, 43, 30, 80, 22, 28, 31, 66],
       [22, 66, 28, 22, 66, 80, 69, 22, 80, 66, 26, 14,  3, 22, 80, 30, 66,
        10, 22, 28, 31, 

In [10]:
y

array([[ 31.,  30.,  44.,  28.,  64.,  26.,  22.,  60.,   0.,   0.,   0.,
         58.,  30.,  44.,  44.,  63.,  22.,  82.,  30.,  59.,  66.,  19.,
         66.,  64.,  80.,  22.,  30.,  26.,  64.,  22.,  30.,  19.,  19.,
         22.,  30.,  19.,  66.,  76.,  64.,  57.,  22.,  64.,  78.,  64.,
         26.,  63.,  22.,  51.,  41.,  67.],
       [ 30.,  59.,  22.,  41.,  12.,  28.,  22.,  68.,  12.,  66.,  41.,
         68.,  22.,  28.,  12.,  22.,  80.,  28.,  30.,  63.,  69.,   3.,
         22.,  30.,  41.,  80.,  43.,  64.,  26.,  64.,  10.,  22.,  34.,
         41.,  41.,  30.,  69.,  22.,  80.,  59.,  66.,  19.,  66.,  41.,
         68.,  69.,  22.,  49.,  51.,  22.],
       [ 66.,  41.,   9.,   0.,   0.,   3.,  54.,  64.,  80.,  69.,  22.,
         66.,  28.,  61.,  80.,  22.,  80.,  64.,  28.,  28.,  19.,  64.,
         10.,   9.,  22.,  65.,  31.,  64.,  22.,  44.,  26.,  66.,  21.,
         64.,  22.,  66.,  80.,  22.,  59.,  30.,  68.,  41.,  66.,  82.,
         66.,  21.,  6

If you implemented `get_batches` correctly, the above output should look something like 
```
x
 [[55 63 69 22  6 76 45  5 16 35]
 [ 5 69  1  5 12 52  6  5 56 52]
 [48 29 12 61 35 35  8 64 76 78]
 [12  5 24 39 45 29 12 56  5 63]
 [ 5 29  6  5 29 78 28  5 78 29]
 [ 5 13  6  5 36 69 78 35 52 12]
 [63 76 12  5 18 52  1 76  5 58]
 [34  5 73 39  6  5 12 52 36  5]
 [ 6  5 29 78 12 79  6 61  5 59]
 [ 5 78 69 29 24  5  6 52  5 63]]

y
 [[63 69 22  6 76 45  5 16 35 35]
 [69  1  5 12 52  6  5 56 52 29]
 [29 12 61 35 35  8 64 76 78 28]
 [ 5 24 39 45 29 12 56  5 63 29]
 [29  6  5 29 78 28  5 78 29 45]
 [13  6  5 36 69 78 35 52 12 43]
 [76 12  5 18 52  1 76  5 58 52]
 [ 5 73 39  6  5 12 52 36  5 78]
 [ 5 29 78 12 79  6 61  5 59 63]
 [78 69 29 24  5  6 52  5 63 76]]
 ```
 although the exact numbers will be different. Check to make sure the data is shifted over one step for `y`.

## Building the model

Below is where you'll build the network. We'll break it up into parts so it's easier to reason about each bit. Then we can connect them up into the whole network.

<img src="assets/charRNN.png" width=500px>


### Inputs

First off we'll create our input placeholders. As usual we need placeholders for the training data and the targets. We'll also create a placeholder for dropout layers called `keep_prob`. This will be a scalar, that is a 0-D tensor. To make a scalar, you create a placeholder without giving it a size.

> **Exercise:** Create the input placeholders in the function below.

In [11]:
def build_inputs(batch_size, num_steps):
    ''' Define placeholders for inputs, targets, and dropout 
    
        Arguments
        ---------
        batch_size: Batch size, number of sequences per batch
        num_steps: Number of sequence steps in a batch
        
    '''
    # Declare placeholders we'll feed into the graph
    inputs = tf.placeholder(tf.int32,[batch_size,num_steps],name="inputs")
    targets = tf.placeholder(tf.int32,[batch_size,num_steps],name="targets")
    
    # Keep probability placeholder for drop out layers
    keep_prob = tf.placeholder(tf.float32,name="keep_prob")
    
    return inputs, targets, keep_prob

### LSTM Cell

Here we will create the LSTM cell we'll use in the hidden layer. We'll use this cell as a building block for the RNN. So we aren't actually defining the RNN here, just the type of cell we'll use in the hidden layer.

We first create a basic LSTM cell with

```python
lstm = tf.contrib.rnn.BasicLSTMCell(num_units)
```

where `num_units` is the number of units in the hidden layers in the cell. Then we can add dropout by wrapping it with 

```python
tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
```
You pass in a cell and it will automatically add dropout to the inputs or outputs. Finally, we can stack up the LSTM cells into layers with [`tf.contrib.rnn.MultiRNNCell`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/contrib/rnn/MultiRNNCell). With this, you pass in a list of cells and it will send the output of one cell into the next cell. For example,

```python
tf.contrib.rnn.MultiRNNCell([cell]*num_layers)
```

This might look a little weird if you know Python well because this will create a list of the same `cell` object. However, TensorFlow will create different weight matrices for all `cell` objects. Even though this is actually multiple LSTM cells stacked on each other, you can treat the multiple layers as one cell.

We also need to create an initial cell state of all zeros. This can be done like so

```python
initial_state = cell.zero_state(batch_size, tf.float32)
```

> **Exercise:** Below, implement the `build_lstm` function to create these LSTM cells and the initial state.

In [32]:
def build_lstm(lstm_size, num_layers, batch_size, keep_prob):
    ''' Build LSTM cell.
    
        Arguments
        ---------
        keep_prob: Scalar tensor (tf.placeholder) for the dropout keep probability
        lstm_size: Size of the hidden layers in the LSTM cells
        num_layers: Number of LSTM layers
        batch_size: Batch size

    '''
    ### Build the LSTM Cell
    # Use a basic LSTM cell
    lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size)
    
    
    # Add dropout to the cell outputs
    drop = tf.contrib.rnn.DropoutWrapper(lstm,output_keep_prob=keep_prob)

    # Stack up multiple LSTM layers, for deep learning
    cell = tf.contrib.rnn.MultiRNNCell([tf.contrib.rnn.BasicLSTMCell(lstm_size) for _ in range(num_layers)])
    initial_state = cell.zero_state(batch_size,tf.float32)
    
    return cell, initial_state

### RNN Output

Here we'll create the output layer. We need to connect the output of the RNN cells to a full connected layer with a softmax output. The softmax output gives us a probability distribution we can use to predict the next character, so we want this layer to have size $C$, the number of classes/characters we have in our text.

If our input has batch size $N$, number of steps $M$, and the hidden layer has $L$ hidden units, then the output is a 3D tensor with size $N \times M \times L$. The output of each LSTM cell has size $L$, we have $M$ of them, one for each sequence step, and we have $N$ sequences. So the total size is $N \times M \times L$. 

We are using the same fully connected layer, the same weights, for each of the outputs. Then, to make things easier, we should reshape the outputs into a 2D tensor with shape $(M * N) \times L$. That is, one row for each sequence and step, where the values of each row are the output from the LSTM cells. We get the LSTM output as a list, `lstm_output`. First we need to concatenate this whole list into one array with [`tf.concat`](https://www.tensorflow.org/api_docs/python/tf/concat). Then, reshape it (with `tf.reshape`) to size $(M * N) \times L$.

One we have the outputs reshaped, we can do the matrix multiplication with the weights. We need to wrap the weight and bias variables in a variable scope with `tf.variable_scope(scope_name)` because there are weights being created in the LSTM cells. TensorFlow will throw an error if the weights created here have the same names as the weights created in the LSTM cells, which they will be default. To avoid this, we wrap the variables in a variable scope so we can give them unique names.

> **Exercise:** Implement the output layer in the function below.

In [38]:
def build_output(lstm_output, in_size, out_size):
    ''' Build a softmax layer, return the softmax output and logits.
    
        Arguments
        ---------
        
        lstm_output: List of output tensors from the LSTM layer
        in_size: Size of the input tensor, for example, size of the LSTM cells
        out_size: Size of this softmax layer
    
    '''

    # Reshape output so it's a bunch of rows, one row for each step for each sequence.
    # Concatenate lstm_output over axis 1 (the columns)
    seq_output = tf.concat(lstm_output,axis=1)
    # Reshape seq_output to a 2D tensor with lstm_size columns
    x = tf.reshape(seq_output,[-1,in_size])
    
    # Connect the RNN outputs to a softmax layer
    with tf.variable_scope('softmax'):
        # Create the weight and bias variables here
        softmax_w = tf.Variable(tf.truncated_normal((in_size, out_size),stddev=0.1))
        softmax_b = tf.Variable(tf.zeros([out_size]))
    
    # Since output is a bunch of rows of RNN cell outputs, logits will be a bunch
    # of rows of logit outputs, one for each step and sequence
    logits =  tf.add(tf.matmul(x,softmax_w),softmax_b) 
    
    # Use softmax to get the probabilities for predicted characters
    out = tf.nn.softmax(logits,name ="out")
    print(out)
    return out, logits

### Training loss

Next up is the training loss. We get the logits and targets and calculate the softmax cross-entropy loss. First we need to one-hot encode the targets, we're getting them as encoded characters. Then, reshape the one-hot targets so it's a 2D tensor with size $(M*N) \times C$ where $C$ is the number of classes/characters we have. Remember that we reshaped the LSTM outputs and ran them through a fully connected layer with $C$ units. So our logits will also have size $(M*N) \times C$.

Then we run the logits and targets through `tf.nn.softmax_cross_entropy_with_logits` and find the mean to get the loss.

>**Exercise:** Implement the loss calculation in the function below.

In [35]:
def build_loss(logits, targets, lstm_size, num_classes):
    ''' Calculate the loss from the logits and the targets.
    
        Arguments
        ---------
        logits: Logits from final fully connected layer
        targets: Targets for supervised learning
        lstm_size: Number of LSTM hidden units
        num_classes: Number of classes in targets
        
    '''
    print(logits)
    print(targets)
    # One-hot encode targets and reshape to match logits, one row per sequence per step
    y_one_hot = tf.one_hot(targets,num_classes)
    y_reshaped =  tf.reshape(y_one_hot,logits.get_shape())
    
    # Softmax cross entropy loss
    loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits,labels=y_reshaped))
    
    return loss

### Optimizer

Here we build the optimizer. Normal RNNs have have issues gradients exploding and disappearing. LSTMs fix the disappearance problem, but the gradients can still grow without bound. To fix this, we can clip the gradients above some threshold. That is, if a gradient is larger than that threshold, we set it to the threshold. This will ensure the gradients never grow overly large. Then we use an AdamOptimizer for the learning step.

In [15]:
def build_optimizer(loss, learning_rate, grad_clip):
    ''' Build optmizer for training, using gradient clipping.
    
        Arguments:
        loss: Network loss
        learning_rate: Learning rate for optimizer
    
    '''
    
    # Optimizer for training, using gradient clipping to control exploding gradients
    tvars = tf.trainable_variables()
    grads, _ = tf.clip_by_global_norm(tf.gradients(loss, tvars), grad_clip)
    train_op = tf.train.AdamOptimizer(learning_rate)
    optimizer = train_op.apply_gradients(zip(grads, tvars))
    
    return optimizer

### Build the network

Now we can put all the pieces together and build a class for the network. To actually run data through the LSTM cells, we will use [`tf.nn.dynamic_rnn`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/nn/dynamic_rnn). This function will pass the hidden and cell states across LSTM cells appropriately for us. It returns the outputs for each LSTM cell at each step for each sequence in the mini-batch. It also gives us the final LSTM state. We want to save this state as `final_state` so we can pass it to the first LSTM cell in the the next mini-batch run. For `tf.nn.dynamic_rnn`, we pass in the cell and initial state we get from `build_lstm`, as well as our input sequences. Also, we need to one-hot encode the inputs before going into the RNN. 

> **Exercise:** Use the functions you've implemented previously and `tf.nn.dynamic_rnn` to build the network.

In [41]:
class CharRNN:
    
    def __init__(self, num_classes, batch_size=64, num_steps=50, 
                       lstm_size=128, num_layers=2, learning_rate=0.001, 
                       grad_clip=5, sampling=False):
    
        # When we're using this network for sampling later, we'll be passing in
        # one character at a time, so providing an option for that
        if sampling == True:
            batch_size, num_steps = 1, 1
        else:
            batch_size, num_steps = batch_size, num_steps

        tf.reset_default_graph()
        
        # Build the input placeholder tensors
        self.inputs, self.targets, self.keep_prob = build_inputs(batch_size,num_steps)
        # Build the LSTM cell
        cell, self.initial_state = build_lstm(lstm_size,num_layers,batch_size,self.keep_prob)
        ### Run the data through the RNN layers
        # First, one-hot encode the input tokens
        x_one_hot = tf.one_hot(self.inputs,num_classes)
        
        # Run each sequence step through the RNN with tf.nn.dynamic_rnn 
        outputs, state = tf.nn.dynamic_rnn(cell,x_one_hot,initial_state=self.initial_state)
        self.final_state = state
        
        # Get softmax predictions and logits
        self.prediction, self.logits = build_output(outputs,lstm_size,num_classes)
        
        # Loss and optimizer (with gradient clipping)
        self.loss =  build_loss(self.logits,self.targets,lstm_size,num_classes)
        self.optimizer = build_optimizer(self.loss,learning_rate,grad_clip)

## Hyperparameters

Here are the hyperparameters for the network.

* `batch_size` - Number of sequences running through the network in one pass.
* `num_steps` - Number of characters in the sequence the network is trained on. Larger is better typically, the network will learn more long range dependencies. But it takes longer to train. 100 is typically a good number here.
* `lstm_size` - The number of units in the hidden layers.
* `num_layers` - Number of hidden LSTM layers to use
* `learning_rate` - Learning rate for training
* `keep_prob` - The dropout keep probability when training. If you're network is overfitting, try decreasing this.

Here's some good advice from Andrej Karpathy on training the network. I'm going to copy it in here for your benefit, but also link to [where it originally came from](https://github.com/karpathy/char-rnn#tips-and-tricks).

> ## Tips and Tricks

>### Monitoring Validation Loss vs. Training Loss
>If you're somewhat new to Machine Learning or Neural Networks it can take a bit of expertise to get good models. The most important quantity to keep track of is the difference between your training loss (printed during training) and the validation loss (printed once in a while when the RNN is run on the validation data (by default every 1000 iterations)). In particular:

> - If your training loss is much lower than validation loss then this means the network might be **overfitting**. Solutions to this are to decrease your network size, or to increase dropout. For example you could try dropout of 0.5 and so on.
> - If your training/validation loss are about equal then your model is **underfitting**. Increase the size of your model (either number of layers or the raw number of neurons per layer)

> ### Approximate number of parameters

> The two most important parameters that control the model are `lstm_size` and `num_layers`. I would advise that you always use `num_layers` of either 2/3. The `lstm_size` can be adjusted based on how much data you have. The two important quantities to keep track of here are:

> - The number of parameters in your model. This is printed when you start training.
> - The size of your dataset. 1MB file is approximately 1 million characters.

>These two should be about the same order of magnitude. It's a little tricky to tell. Here are some examples:

> - I have a 100MB dataset and I'm using the default parameter settings (which currently print 150K parameters). My data size is significantly larger (100 mil >> 0.15 mil), so I expect to heavily underfit. I am thinking I can comfortably afford to make `lstm_size` larger.
> - I have a 10MB dataset and running a 10 million parameter model. I'm slightly nervous and I'm carefully monitoring my validation loss. If it's larger than my training loss then I may want to try to increase dropout a bit and see if that helps the validation loss.

> ### Best models strategy

>The winning strategy to obtaining very good models (if you have the compute time) is to always err on making the network larger (as large as you're willing to wait for it to compute) and then try different dropout values (between 0,1). Whatever model has the best validation performance (the loss, written in the checkpoint filename, low is good) is the one you should use in the end.

>It is very common in deep learning to run many different models with many different hyperparameter settings, and in the end take whatever checkpoint gave the best validation performance.

>By the way, the size of your training and validation splits are also parameters. Make sure you have a decent amount of data in your validation set or otherwise the validation performance will be noisy and not very informative.

In [17]:
batch_size = 100         # Sequences per batch
num_steps = 50          # Number of sequence steps per batch
lstm_size = 512         # Size of hidden layers in LSTMs
num_layers = 3          # Number of LSTM layers
learning_rate = 0.01    # Learning rate
keep_prob = 0.5         # Dropout keep probability

## Time for training

This is typical training code, passing inputs and targets into the network, then running the optimizer. Here we also get back the final LSTM state for the mini-batch. Then, we pass that state back into the network so the next batch can continue the state from the previous batch. And every so often (set by `save_every_n`) I save a checkpoint.

Here I'm saving checkpoints with the format

`i{iteration number}_l{# hidden layer units}.ckpt`

> **Exercise:** Set the hyperparameters above to train the network. Watch the training loss, it should be consistently dropping. Also, I highly advise running this on a GPU.

In [43]:
epochs = 20
# Save every N iterations
save_every_n = 200
with tf.device("/cpu:0"):
    model = CharRNN(len(vocab), batch_size=batch_size, num_steps=num_steps,
                lstm_size=lstm_size, num_layers=num_layers, 
                learning_rate=learning_rate)

saver = tf.train.Saver(max_to_keep=100)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    # Use the line below to load a checkpoint and resume training
    #saver.restore(sess, 'checkpoints/______.ckpt')
    counter = 0
    for e in range(epochs):
        # Train network
        new_state = sess.run(model.initial_state)
        loss = 0
        for x, y in get_batches(encoded, batch_size, num_steps):
            counter += 1
            start = time.time()
            feed = {model.inputs: x,
                    model.targets: y,
                    model.keep_prob: keep_prob,
                    model.initial_state: new_state}
            batch_loss, new_state, _ = sess.run([model.loss, 
                                                 model.final_state, 
                                                 model.optimizer], 
                                                 feed_dict=feed)
            
            end = time.time()
            print('Epoch: {}/{}... '.format(e+1, epochs),
                  'Training Step: {}... '.format(counter),
                  'Training loss: {:.4f}... '.format(batch_loss),
                  '{:.4f} sec/batch'.format((end-start)))
        
            if (counter % save_every_n == 0):
                saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))
    
    saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))

Tensor("out:0", shape=(5000, 83), dtype=float32)
Tensor("Add:0", shape=(5000, 83), dtype=float32)
Tensor("targets:0", shape=(100, 50), dtype=int32)
Epoch: 1/20...  Training Step: 1...  Training loss: 4.4191...  2.3202 sec/batch
Epoch: 1/20...  Training Step: 2...  Training loss: 3.7052...  2.3488 sec/batch
Epoch: 1/20...  Training Step: 3...  Training loss: 5.5688...  2.5315 sec/batch
Epoch: 1/20...  Training Step: 4...  Training loss: 6.8322...  2.9516 sec/batch
Epoch: 1/20...  Training Step: 5...  Training loss: 4.1952...  2.5303 sec/batch
Epoch: 1/20...  Training Step: 6...  Training loss: 3.9273...  2.7738 sec/batch
Epoch: 1/20...  Training Step: 7...  Training loss: 3.6086...  2.8774 sec/batch
Epoch: 1/20...  Training Step: 8...  Training loss: 3.4473...  2.8274 sec/batch
Epoch: 1/20...  Training Step: 9...  Training loss: 3.2708...  2.7117 sec/batch
Epoch: 1/20...  Training Step: 10...  Training loss: 3.1710...  2.7566 sec/batch
Epoch: 1/20...  Training Step: 11...  Training loss

Epoch: 1/20...  Training Step: 101...  Training loss: 3.1068...  3.2214 sec/batch
Epoch: 1/20...  Training Step: 102...  Training loss: 3.0967...  2.8619 sec/batch
Epoch: 1/20...  Training Step: 103...  Training loss: 3.1170...  2.7910 sec/batch
Epoch: 1/20...  Training Step: 104...  Training loss: 3.0966...  3.2761 sec/batch
Epoch: 1/20...  Training Step: 105...  Training loss: 3.1233...  2.8386 sec/batch
Epoch: 1/20...  Training Step: 106...  Training loss: 3.1092...  3.2849 sec/batch
Epoch: 1/20...  Training Step: 107...  Training loss: 3.1099...  3.0916 sec/batch
Epoch: 1/20...  Training Step: 108...  Training loss: 3.1031...  2.9271 sec/batch
Epoch: 1/20...  Training Step: 109...  Training loss: 3.1277...  3.0837 sec/batch
Epoch: 1/20...  Training Step: 110...  Training loss: 3.0956...  2.9439 sec/batch
Epoch: 1/20...  Training Step: 111...  Training loss: 3.1116...  3.2558 sec/batch
Epoch: 1/20...  Training Step: 112...  Training loss: 3.1188...  2.8242 sec/batch
Epoch: 1/20...  

Epoch: 1/20...  Training Step: 201...  Training loss: 3.1155...  2.6457 sec/batch
Epoch: 1/20...  Training Step: 202...  Training loss: 3.1313...  3.0371 sec/batch
Epoch: 1/20...  Training Step: 203...  Training loss: 3.1123...  2.8109 sec/batch
Epoch: 1/20...  Training Step: 204...  Training loss: 3.1396...  2.9239 sec/batch
Epoch: 1/20...  Training Step: 205...  Training loss: 3.0928...  2.8623 sec/batch
Epoch: 1/20...  Training Step: 206...  Training loss: 3.1215...  3.2511 sec/batch
Epoch: 1/20...  Training Step: 207...  Training loss: 3.1287...  3.0270 sec/batch
Epoch: 1/20...  Training Step: 208...  Training loss: 3.1225...  2.9383 sec/batch
Epoch: 1/20...  Training Step: 209...  Training loss: 3.1148...  3.2984 sec/batch
Epoch: 1/20...  Training Step: 210...  Training loss: 3.1000...  2.8796 sec/batch
Epoch: 1/20...  Training Step: 211...  Training loss: 3.1369...  3.0065 sec/batch
Epoch: 1/20...  Training Step: 212...  Training loss: 3.1093...  3.0083 sec/batch
Epoch: 1/20...  

Epoch: 1/20...  Training Step: 301...  Training loss: 3.1454...  3.7466 sec/batch
Epoch: 1/20...  Training Step: 302...  Training loss: 3.1026...  4.5026 sec/batch
Epoch: 1/20...  Training Step: 303...  Training loss: 3.1316...  3.9913 sec/batch
Epoch: 1/20...  Training Step: 304...  Training loss: 3.0869...  4.0267 sec/batch
Epoch: 1/20...  Training Step: 305...  Training loss: 3.0999...  3.4494 sec/batch
Epoch: 1/20...  Training Step: 306...  Training loss: 3.1235...  3.5116 sec/batch
Epoch: 1/20...  Training Step: 307...  Training loss: 3.1102...  3.8519 sec/batch
Epoch: 1/20...  Training Step: 308...  Training loss: 3.1161...  3.3612 sec/batch
Epoch: 1/20...  Training Step: 309...  Training loss: 3.1364...  3.1151 sec/batch
Epoch: 1/20...  Training Step: 310...  Training loss: 3.1156...  3.4663 sec/batch
Epoch: 1/20...  Training Step: 311...  Training loss: 3.1418...  3.4095 sec/batch
Epoch: 1/20...  Training Step: 312...  Training loss: 3.1184...  3.3123 sec/batch
Epoch: 1/20...  

Epoch: 2/20...  Training Step: 401...  Training loss: 3.1315...  2.6787 sec/batch
Epoch: 2/20...  Training Step: 402...  Training loss: 3.1275...  2.7096 sec/batch
Epoch: 2/20...  Training Step: 403...  Training loss: 3.1143...  3.0477 sec/batch
Epoch: 2/20...  Training Step: 404...  Training loss: 3.1046...  2.8202 sec/batch
Epoch: 2/20...  Training Step: 405...  Training loss: 3.1609...  2.7774 sec/batch
Epoch: 2/20...  Training Step: 406...  Training loss: 3.1612...  2.8425 sec/batch
Epoch: 2/20...  Training Step: 407...  Training loss: 3.1321...  3.0881 sec/batch
Epoch: 2/20...  Training Step: 408...  Training loss: 3.1339...  2.8100 sec/batch
Epoch: 2/20...  Training Step: 409...  Training loss: 3.1120...  2.6949 sec/batch
Epoch: 2/20...  Training Step: 410...  Training loss: 3.0988...  2.9390 sec/batch
Epoch: 2/20...  Training Step: 411...  Training loss: 3.1405...  2.7696 sec/batch
Epoch: 2/20...  Training Step: 412...  Training loss: 3.0795...  2.8079 sec/batch
Epoch: 2/20...  

Epoch: 2/20...  Training Step: 501...  Training loss: 3.0946...  2.8925 sec/batch
Epoch: 2/20...  Training Step: 502...  Training loss: 3.1222...  2.7840 sec/batch
Epoch: 2/20...  Training Step: 503...  Training loss: 3.1090...  2.9807 sec/batch
Epoch: 2/20...  Training Step: 504...  Training loss: 3.1096...  2.6197 sec/batch
Epoch: 2/20...  Training Step: 505...  Training loss: 3.1047...  2.6180 sec/batch
Epoch: 2/20...  Training Step: 506...  Training loss: 3.1278...  2.7055 sec/batch
Epoch: 2/20...  Training Step: 507...  Training loss: 3.0926...  3.1297 sec/batch
Epoch: 2/20...  Training Step: 508...  Training loss: 3.1089...  2.9158 sec/batch
Epoch: 2/20...  Training Step: 509...  Training loss: 3.1186...  2.8474 sec/batch
Epoch: 2/20...  Training Step: 510...  Training loss: 3.1138...  3.0852 sec/batch
Epoch: 2/20...  Training Step: 511...  Training loss: 3.1441...  2.7374 sec/batch
Epoch: 2/20...  Training Step: 512...  Training loss: 3.1266...  2.7177 sec/batch
Epoch: 2/20...  

Epoch: 2/20...  Training Step: 601...  Training loss: 3.1387...  2.5836 sec/batch
Epoch: 2/20...  Training Step: 602...  Training loss: 3.0925...  2.5689 sec/batch
Epoch: 2/20...  Training Step: 603...  Training loss: 3.1221...  2.8362 sec/batch
Epoch: 2/20...  Training Step: 604...  Training loss: 3.1260...  2.7131 sec/batch
Epoch: 2/20...  Training Step: 605...  Training loss: 3.1220...  2.7722 sec/batch
Epoch: 2/20...  Training Step: 606...  Training loss: 3.1147...  2.9398 sec/batch
Epoch: 2/20...  Training Step: 607...  Training loss: 3.1007...  2.7060 sec/batch
Epoch: 2/20...  Training Step: 608...  Training loss: 3.1368...  2.6406 sec/batch
Epoch: 2/20...  Training Step: 609...  Training loss: 3.1105...  2.8143 sec/batch
Epoch: 2/20...  Training Step: 610...  Training loss: 3.1431...  2.9654 sec/batch
Epoch: 2/20...  Training Step: 611...  Training loss: 3.1166...  2.6463 sec/batch
Epoch: 2/20...  Training Step: 612...  Training loss: 3.1351...  2.6595 sec/batch
Epoch: 2/20...  

Epoch: 2/20...  Training Step: 701...  Training loss: 3.0865...  2.8241 sec/batch
Epoch: 2/20...  Training Step: 702...  Training loss: 3.0982...  2.8205 sec/batch
Epoch: 2/20...  Training Step: 703...  Training loss: 3.1219...  3.2439 sec/batch
Epoch: 2/20...  Training Step: 704...  Training loss: 3.1081...  3.0090 sec/batch
Epoch: 2/20...  Training Step: 705...  Training loss: 3.1142...  2.7619 sec/batch
Epoch: 2/20...  Training Step: 706...  Training loss: 3.1357...  2.9538 sec/batch
Epoch: 2/20...  Training Step: 707...  Training loss: 3.1161...  2.9793 sec/batch
Epoch: 2/20...  Training Step: 708...  Training loss: 3.1396...  3.0532 sec/batch
Epoch: 2/20...  Training Step: 709...  Training loss: 3.1166...  2.7938 sec/batch
Epoch: 2/20...  Training Step: 710...  Training loss: 3.1250...  3.0408 sec/batch
Epoch: 2/20...  Training Step: 711...  Training loss: 3.1027...  2.8377 sec/batch
Epoch: 2/20...  Training Step: 712...  Training loss: 3.1233...  2.9673 sec/batch
Epoch: 2/20...  

Epoch: 3/20...  Training Step: 801...  Training loss: 3.0939...  2.7782 sec/batch
Epoch: 3/20...  Training Step: 802...  Training loss: 3.1434...  3.1651 sec/batch
Epoch: 3/20...  Training Step: 803...  Training loss: 3.1463...  3.7129 sec/batch
Epoch: 3/20...  Training Step: 804...  Training loss: 3.1143...  3.2361 sec/batch
Epoch: 3/20...  Training Step: 805...  Training loss: 3.1249...  3.1744 sec/batch
Epoch: 3/20...  Training Step: 806...  Training loss: 3.1111...  3.4918 sec/batch
Epoch: 3/20...  Training Step: 807...  Training loss: 3.0960...  2.9455 sec/batch
Epoch: 3/20...  Training Step: 808...  Training loss: 3.1307...  2.9272 sec/batch
Epoch: 3/20...  Training Step: 809...  Training loss: 3.0694...  3.5794 sec/batch
Epoch: 3/20...  Training Step: 810...  Training loss: 3.1252...  2.9802 sec/batch
Epoch: 3/20...  Training Step: 811...  Training loss: 3.0998...  2.9379 sec/batch
Epoch: 3/20...  Training Step: 812...  Training loss: 3.0850...  2.8864 sec/batch
Epoch: 3/20...  

Epoch: 3/20...  Training Step: 901...  Training loss: 3.1084...  2.6570 sec/batch
Epoch: 3/20...  Training Step: 902...  Training loss: 3.1020...  2.9710 sec/batch
Epoch: 3/20...  Training Step: 903...  Training loss: 3.1236...  3.4978 sec/batch
Epoch: 3/20...  Training Step: 904...  Training loss: 3.0896...  3.4369 sec/batch
Epoch: 3/20...  Training Step: 905...  Training loss: 3.1070...  2.7984 sec/batch
Epoch: 3/20...  Training Step: 906...  Training loss: 3.1144...  2.7914 sec/batch
Epoch: 3/20...  Training Step: 907...  Training loss: 3.1146...  3.1989 sec/batch
Epoch: 3/20...  Training Step: 908...  Training loss: 3.1401...  2.8663 sec/batch
Epoch: 3/20...  Training Step: 909...  Training loss: 3.1275...  2.6723 sec/batch
Epoch: 3/20...  Training Step: 910...  Training loss: 3.1432...  3.1383 sec/batch
Epoch: 3/20...  Training Step: 911...  Training loss: 3.1217...  2.6713 sec/batch
Epoch: 3/20...  Training Step: 912...  Training loss: 3.1218...  2.6017 sec/batch
Epoch: 3/20...  

Epoch: 3/20...  Training Step: 1001...  Training loss: 2.9711...  2.7570 sec/batch
Epoch: 3/20...  Training Step: 1002...  Training loss: 2.9697...  2.6786 sec/batch
Epoch: 3/20...  Training Step: 1003...  Training loss: 2.9721...  2.7127 sec/batch
Epoch: 3/20...  Training Step: 1004...  Training loss: 2.9679...  2.7921 sec/batch
Epoch: 3/20...  Training Step: 1005...  Training loss: 2.9901...  3.0458 sec/batch
Epoch: 3/20...  Training Step: 1006...  Training loss: 2.9686...  2.6766 sec/batch
Epoch: 3/20...  Training Step: 1007...  Training loss: 2.9816...  2.5910 sec/batch
Epoch: 3/20...  Training Step: 1008...  Training loss: 2.9729...  2.7605 sec/batch
Epoch: 3/20...  Training Step: 1009...  Training loss: 2.9892...  2.7263 sec/batch
Epoch: 3/20...  Training Step: 1010...  Training loss: 2.9345...  2.6112 sec/batch
Epoch: 3/20...  Training Step: 1011...  Training loss: 2.9252...  2.6499 sec/batch
Epoch: 3/20...  Training Step: 1012...  Training loss: 2.9577...  2.9515 sec/batch
Epoc

Epoch: 3/20...  Training Step: 1100...  Training loss: 2.9233...  3.5025 sec/batch
Epoch: 3/20...  Training Step: 1101...  Training loss: 2.9595...  2.6466 sec/batch
Epoch: 3/20...  Training Step: 1102...  Training loss: 2.8344...  2.5665 sec/batch
Epoch: 3/20...  Training Step: 1103...  Training loss: 2.9481...  2.8899 sec/batch
Epoch: 3/20...  Training Step: 1104...  Training loss: 2.8763...  2.4590 sec/batch
Epoch: 3/20...  Training Step: 1105...  Training loss: 2.9538...  2.4085 sec/batch
Epoch: 3/20...  Training Step: 1106...  Training loss: 2.8641...  2.5054 sec/batch
Epoch: 3/20...  Training Step: 1107...  Training loss: 2.9585...  2.7735 sec/batch
Epoch: 3/20...  Training Step: 1108...  Training loss: 2.9111...  2.4561 sec/batch
Epoch: 3/20...  Training Step: 1109...  Training loss: 2.9792...  2.4295 sec/batch
Epoch: 3/20...  Training Step: 1110...  Training loss: 2.8604...  2.4028 sec/batch
Epoch: 3/20...  Training Step: 1111...  Training loss: 2.9030...  2.5771 sec/batch
Epoc

Epoch: 4/20...  Training Step: 1199...  Training loss: 2.8549...  3.0834 sec/batch
Epoch: 4/20...  Training Step: 1200...  Training loss: 3.1042...  2.6913 sec/batch
Epoch: 4/20...  Training Step: 1201...  Training loss: 2.9254...  2.2700 sec/batch
Epoch: 4/20...  Training Step: 1202...  Training loss: 2.8868...  2.3404 sec/batch
Epoch: 4/20...  Training Step: 1203...  Training loss: 2.8384...  2.9241 sec/batch
Epoch: 4/20...  Training Step: 1204...  Training loss: 2.8168...  3.1224 sec/batch
Epoch: 4/20...  Training Step: 1205...  Training loss: 2.8379...  2.9993 sec/batch
Epoch: 4/20...  Training Step: 1206...  Training loss: 2.7677...  3.5097 sec/batch
Epoch: 4/20...  Training Step: 1207...  Training loss: 2.7978...  2.8114 sec/batch
Epoch: 4/20...  Training Step: 1208...  Training loss: 2.8205...  2.6807 sec/batch
Epoch: 4/20...  Training Step: 1209...  Training loss: 2.7718...  2.6911 sec/batch
Epoch: 4/20...  Training Step: 1210...  Training loss: 2.7534...  2.6030 sec/batch
Epoc

Epoch: 4/20...  Training Step: 1298...  Training loss: 2.7084...  2.4582 sec/batch
Epoch: 4/20...  Training Step: 1299...  Training loss: 2.6841...  2.3979 sec/batch
Epoch: 4/20...  Training Step: 1300...  Training loss: 2.7217...  2.4470 sec/batch
Epoch: 4/20...  Training Step: 1301...  Training loss: 2.6900...  2.5981 sec/batch
Epoch: 4/20...  Training Step: 1302...  Training loss: 2.6944...  2.7261 sec/batch
Epoch: 4/20...  Training Step: 1303...  Training loss: 2.6909...  2.3860 sec/batch
Epoch: 4/20...  Training Step: 1304...  Training loss: 2.6708...  2.5260 sec/batch
Epoch: 4/20...  Training Step: 1305...  Training loss: 2.7207...  2.7401 sec/batch
Epoch: 4/20...  Training Step: 1306...  Training loss: 2.7177...  2.5538 sec/batch
Epoch: 4/20...  Training Step: 1307...  Training loss: 2.7283...  2.3668 sec/batch
Epoch: 4/20...  Training Step: 1308...  Training loss: 2.6818...  2.3313 sec/batch
Epoch: 4/20...  Training Step: 1309...  Training loss: 2.6953...  2.4118 sec/batch
Epoc

Epoch: 4/20...  Training Step: 1397...  Training loss: 2.6508...  2.3837 sec/batch
Epoch: 4/20...  Training Step: 1398...  Training loss: 2.6345...  2.3766 sec/batch
Epoch: 4/20...  Training Step: 1399...  Training loss: 2.6266...  2.9147 sec/batch
Epoch: 4/20...  Training Step: 1400...  Training loss: 2.6467...  2.3989 sec/batch
Epoch: 4/20...  Training Step: 1401...  Training loss: 2.6577...  2.3261 sec/batch
Epoch: 4/20...  Training Step: 1402...  Training loss: 2.6727...  2.3541 sec/batch
Epoch: 4/20...  Training Step: 1403...  Training loss: 2.6558...  2.6864 sec/batch
Epoch: 4/20...  Training Step: 1404...  Training loss: 2.6634...  2.3641 sec/batch
Epoch: 4/20...  Training Step: 1405...  Training loss: 2.6594...  2.4056 sec/batch
Epoch: 4/20...  Training Step: 1406...  Training loss: 2.6443...  2.4447 sec/batch
Epoch: 4/20...  Training Step: 1407...  Training loss: 2.6210...  2.7720 sec/batch
Epoch: 4/20...  Training Step: 1408...  Training loss: 2.6394...  2.3878 sec/batch
Epoc

Epoch: 4/20...  Training Step: 1496...  Training loss: 2.7322...  2.4733 sec/batch
Epoch: 4/20...  Training Step: 1497...  Training loss: 2.7367...  2.6151 sec/batch
Epoch: 4/20...  Training Step: 1498...  Training loss: 2.7280...  2.6322 sec/batch
Epoch: 4/20...  Training Step: 1499...  Training loss: 2.7248...  2.6566 sec/batch
Epoch: 4/20...  Training Step: 1500...  Training loss: 2.7305...  2.5774 sec/batch
Epoch: 4/20...  Training Step: 1501...  Training loss: 2.7226...  2.5712 sec/batch
Epoch: 4/20...  Training Step: 1502...  Training loss: 2.7297...  2.3808 sec/batch
Epoch: 4/20...  Training Step: 1503...  Training loss: 2.7139...  2.4028 sec/batch
Epoch: 4/20...  Training Step: 1504...  Training loss: 2.7183...  2.4660 sec/batch
Epoch: 4/20...  Training Step: 1505...  Training loss: 2.7238...  2.6253 sec/batch
Epoch: 4/20...  Training Step: 1506...  Training loss: 2.7337...  2.3770 sec/batch
Epoch: 4/20...  Training Step: 1507...  Training loss: 2.6817...  2.3789 sec/batch
Epoc

Epoch: 5/20...  Training Step: 1595...  Training loss: 2.5885...  2.4587 sec/batch
Epoch: 5/20...  Training Step: 1596...  Training loss: 2.7433...  2.4410 sec/batch
Epoch: 5/20...  Training Step: 1597...  Training loss: 2.6898...  2.3939 sec/batch
Epoch: 5/20...  Training Step: 1598...  Training loss: 2.7309...  2.6559 sec/batch
Epoch: 5/20...  Training Step: 1599...  Training loss: 2.6402...  2.4376 sec/batch
Epoch: 5/20...  Training Step: 1600...  Training loss: 2.6872...  2.4372 sec/batch
Epoch: 5/20...  Training Step: 1601...  Training loss: 2.5946...  2.2910 sec/batch
Epoch: 5/20...  Training Step: 1602...  Training loss: 2.6803...  2.7372 sec/batch
Epoch: 5/20...  Training Step: 1603...  Training loss: 2.5772...  2.4047 sec/batch
Epoch: 5/20...  Training Step: 1604...  Training loss: 2.6430...  2.4344 sec/batch
Epoch: 5/20...  Training Step: 1605...  Training loss: 2.6192...  2.4483 sec/batch
Epoch: 5/20...  Training Step: 1606...  Training loss: 2.6190...  2.7618 sec/batch
Epoc

Epoch: 5/20...  Training Step: 1694...  Training loss: 2.5181...  2.3797 sec/batch
Epoch: 5/20...  Training Step: 1695...  Training loss: 2.5509...  2.9852 sec/batch
Epoch: 5/20...  Training Step: 1696...  Training loss: 2.5550...  2.5774 sec/batch
Epoch: 5/20...  Training Step: 1697...  Training loss: 2.5808...  2.3902 sec/batch
Epoch: 5/20...  Training Step: 1698...  Training loss: 2.5452...  2.3806 sec/batch
Epoch: 5/20...  Training Step: 1699...  Training loss: 2.5607...  2.6203 sec/batch
Epoch: 5/20...  Training Step: 1700...  Training loss: 2.5342...  2.9030 sec/batch
Epoch: 5/20...  Training Step: 1701...  Training loss: 2.5438...  2.5462 sec/batch
Epoch: 5/20...  Training Step: 1702...  Training loss: 2.5819...  2.3664 sec/batch
Epoch: 5/20...  Training Step: 1703...  Training loss: 2.5879...  2.6531 sec/batch
Epoch: 5/20...  Training Step: 1704...  Training loss: 2.6169...  2.5377 sec/batch
Epoch: 5/20...  Training Step: 1705...  Training loss: 2.5602...  2.7116 sec/batch
Epoc

Epoch: 5/20...  Training Step: 1793...  Training loss: 2.4917...  2.3679 sec/batch
Epoch: 5/20...  Training Step: 1794...  Training loss: 2.5336...  2.4036 sec/batch
Epoch: 5/20...  Training Step: 1795...  Training loss: 2.5235...  3.0038 sec/batch
Epoch: 5/20...  Training Step: 1796...  Training loss: 2.5165...  2.4418 sec/batch
Epoch: 5/20...  Training Step: 1797...  Training loss: 2.5151...  2.4045 sec/batch
Epoch: 5/20...  Training Step: 1798...  Training loss: 2.5038...  2.3676 sec/batch
Epoch: 5/20...  Training Step: 1799...  Training loss: 2.5537...  2.7354 sec/batch
Epoch: 5/20...  Training Step: 1800...  Training loss: 2.5254...  2.7545 sec/batch
Epoch: 5/20...  Training Step: 1801...  Training loss: 2.5279...  2.3151 sec/batch
Epoch: 5/20...  Training Step: 1802...  Training loss: 2.5387...  2.3708 sec/batch
Epoch: 5/20...  Training Step: 1803...  Training loss: 2.5179...  2.6508 sec/batch
Epoch: 5/20...  Training Step: 1804...  Training loss: 2.4999...  2.5365 sec/batch
Epoc

Epoch: 5/20...  Training Step: 1892...  Training loss: 2.4601...  2.4934 sec/batch
Epoch: 5/20...  Training Step: 1893...  Training loss: 2.5005...  2.3944 sec/batch
Epoch: 5/20...  Training Step: 1894...  Training loss: 2.5099...  2.5091 sec/batch
Epoch: 5/20...  Training Step: 1895...  Training loss: 2.5047...  2.6329 sec/batch
Epoch: 5/20...  Training Step: 1896...  Training loss: 2.4913...  2.4406 sec/batch
Epoch: 5/20...  Training Step: 1897...  Training loss: 2.5118...  2.4157 sec/batch
Epoch: 5/20...  Training Step: 1898...  Training loss: 2.5012...  2.4594 sec/batch
Epoch: 5/20...  Training Step: 1899...  Training loss: 2.4930...  2.6863 sec/batch
Epoch: 5/20...  Training Step: 1900...  Training loss: 2.4967...  2.4204 sec/batch
Epoch: 5/20...  Training Step: 1901...  Training loss: 2.5027...  2.4267 sec/batch
Epoch: 5/20...  Training Step: 1902...  Training loss: 2.5109...  2.4348 sec/batch
Epoch: 5/20...  Training Step: 1903...  Training loss: 2.5390...  2.6777 sec/batch
Epoc

Epoch: 6/20...  Training Step: 1991...  Training loss: 2.5397...  2.7801 sec/batch
Epoch: 6/20...  Training Step: 1992...  Training loss: 2.4625...  2.5039 sec/batch
Epoch: 6/20...  Training Step: 1993...  Training loss: 2.5354...  2.4332 sec/batch
Epoch: 6/20...  Training Step: 1994...  Training loss: 2.5428...  2.4577 sec/batch
Epoch: 6/20...  Training Step: 1995...  Training loss: 2.5685...  2.6514 sec/batch
Epoch: 6/20...  Training Step: 1996...  Training loss: 2.5210...  2.7049 sec/batch
Epoch: 6/20...  Training Step: 1997...  Training loss: 2.5546...  2.4848 sec/batch
Epoch: 6/20...  Training Step: 1998...  Training loss: 2.5113...  2.3997 sec/batch
Epoch: 6/20...  Training Step: 1999...  Training loss: 2.5412...  2.5949 sec/batch
Epoch: 6/20...  Training Step: 2000...  Training loss: 2.4842...  2.4628 sec/batch
Epoch: 6/20...  Training Step: 2001...  Training loss: 2.5399...  2.5328 sec/batch
Epoch: 6/20...  Training Step: 2002...  Training loss: 2.5228...  2.6603 sec/batch
Epoc

Epoch: 6/20...  Training Step: 2090...  Training loss: 2.4292...  2.7388 sec/batch
Epoch: 6/20...  Training Step: 2091...  Training loss: 2.4770...  2.4363 sec/batch
Epoch: 6/20...  Training Step: 2092...  Training loss: 2.4876...  2.4248 sec/batch
Epoch: 6/20...  Training Step: 2093...  Training loss: 2.4634...  2.4280 sec/batch
Epoch: 6/20...  Training Step: 2094...  Training loss: 2.5113...  2.6876 sec/batch
Epoch: 6/20...  Training Step: 2095...  Training loss: 2.4680...  2.4350 sec/batch
Epoch: 6/20...  Training Step: 2096...  Training loss: 2.4704...  2.4117 sec/batch
Epoch: 6/20...  Training Step: 2097...  Training loss: 2.4369...  2.4202 sec/batch
Epoch: 6/20...  Training Step: 2098...  Training loss: 2.4459...  2.6904 sec/batch
Epoch: 6/20...  Training Step: 2099...  Training loss: 2.4776...  2.4524 sec/batch
Epoch: 6/20...  Training Step: 2100...  Training loss: 2.5156...  2.4724 sec/batch
Epoch: 6/20...  Training Step: 2101...  Training loss: 2.5394...  2.4401 sec/batch
Epoc

Epoch: 6/20...  Training Step: 2189...  Training loss: 2.4646...  2.4901 sec/batch
Epoch: 6/20...  Training Step: 2190...  Training loss: 2.4206...  2.3988 sec/batch
Epoch: 6/20...  Training Step: 2191...  Training loss: 2.4649...  2.4908 sec/batch
Epoch: 6/20...  Training Step: 2192...  Training loss: 2.4258...  2.6882 sec/batch
Epoch: 6/20...  Training Step: 2193...  Training loss: 2.4326...  2.4292 sec/batch
Epoch: 6/20...  Training Step: 2194...  Training loss: 2.4348...  2.3839 sec/batch
Epoch: 6/20...  Training Step: 2195...  Training loss: 2.4264...  2.4182 sec/batch
Epoch: 6/20...  Training Step: 2196...  Training loss: 2.4710...  2.6959 sec/batch
Epoch: 6/20...  Training Step: 2197...  Training loss: 2.4429...  2.4472 sec/batch
Epoch: 6/20...  Training Step: 2198...  Training loss: 2.4393...  2.3703 sec/batch
Epoch: 6/20...  Training Step: 2199...  Training loss: 2.4591...  2.4197 sec/batch
Epoch: 6/20...  Training Step: 2200...  Training loss: 2.4309...  2.7041 sec/batch
Epoc

Epoch: 6/20...  Training Step: 2288...  Training loss: 2.4025...  2.9834 sec/batch
Epoch: 6/20...  Training Step: 2289...  Training loss: 2.3923...  2.5539 sec/batch
Epoch: 6/20...  Training Step: 2290...  Training loss: 2.4122...  3.1757 sec/batch
Epoch: 6/20...  Training Step: 2291...  Training loss: 2.4154...  3.3192 sec/batch
Epoch: 6/20...  Training Step: 2292...  Training loss: 2.4036...  2.8998 sec/batch
Epoch: 6/20...  Training Step: 2293...  Training loss: 2.3981...  2.9783 sec/batch
Epoch: 6/20...  Training Step: 2294...  Training loss: 2.4392...  3.4555 sec/batch
Epoch: 6/20...  Training Step: 2295...  Training loss: 2.4178...  2.8507 sec/batch
Epoch: 6/20...  Training Step: 2296...  Training loss: 2.4113...  2.7436 sec/batch
Epoch: 6/20...  Training Step: 2297...  Training loss: 2.4175...  2.7381 sec/batch
Epoch: 6/20...  Training Step: 2298...  Training loss: 2.4319...  2.8615 sec/batch
Epoch: 6/20...  Training Step: 2299...  Training loss: 2.4301...  3.6033 sec/batch
Epoc

Epoch: 7/20...  Training Step: 2387...  Training loss: 2.3801...  2.5274 sec/batch
Epoch: 7/20...  Training Step: 2388...  Training loss: 2.3675...  2.4702 sec/batch
Epoch: 7/20...  Training Step: 2389...  Training loss: 2.3740...  2.5031 sec/batch
Epoch: 7/20...  Training Step: 2390...  Training loss: 2.4051...  2.8735 sec/batch
Epoch: 7/20...  Training Step: 2391...  Training loss: 2.4649...  2.6286 sec/batch
Epoch: 7/20...  Training Step: 2392...  Training loss: 2.4200...  2.5801 sec/batch
Epoch: 7/20...  Training Step: 2393...  Training loss: 2.4079...  2.7404 sec/batch
Epoch: 7/20...  Training Step: 2394...  Training loss: 2.4266...  2.5406 sec/batch
Epoch: 7/20...  Training Step: 2395...  Training loss: 2.4241...  2.6207 sec/batch
Epoch: 7/20...  Training Step: 2396...  Training loss: 2.4128...  2.6479 sec/batch
Epoch: 7/20...  Training Step: 2397...  Training loss: 2.3720...  2.9330 sec/batch
Epoch: 7/20...  Training Step: 2398...  Training loss: 2.4367...  2.6841 sec/batch
Epoc

Epoch: 7/20...  Training Step: 2486...  Training loss: 2.3600...  2.8044 sec/batch
Epoch: 7/20...  Training Step: 2487...  Training loss: 2.3651...  2.6163 sec/batch
Epoch: 7/20...  Training Step: 2488...  Training loss: 2.4193...  2.9812 sec/batch
Epoch: 7/20...  Training Step: 2489...  Training loss: 2.4215...  3.0389 sec/batch
Epoch: 7/20...  Training Step: 2490...  Training loss: 2.4175...  2.8405 sec/batch
Epoch: 7/20...  Training Step: 2491...  Training loss: 2.4507...  2.5100 sec/batch
Epoch: 7/20...  Training Step: 2492...  Training loss: 2.3893...  2.5562 sec/batch
Epoch: 7/20...  Training Step: 2493...  Training loss: 2.4209...  2.7100 sec/batch
Epoch: 7/20...  Training Step: 2494...  Training loss: 2.3925...  3.0437 sec/batch
Epoch: 7/20...  Training Step: 2495...  Training loss: 2.3931...  2.6087 sec/batch
Epoch: 7/20...  Training Step: 2496...  Training loss: 2.4549...  2.6573 sec/batch
Epoch: 7/20...  Training Step: 2497...  Training loss: 2.4694...  2.8964 sec/batch
Epoc

Epoch: 7/20...  Training Step: 2585...  Training loss: 2.3792...  2.5730 sec/batch
Epoch: 7/20...  Training Step: 2586...  Training loss: 2.3989...  2.6407 sec/batch
Epoch: 7/20...  Training Step: 2587...  Training loss: 2.3636...  2.9095 sec/batch
Epoch: 7/20...  Training Step: 2588...  Training loss: 2.3999...  2.5206 sec/batch
Epoch: 7/20...  Training Step: 2589...  Training loss: 2.3533...  2.5576 sec/batch
Epoch: 7/20...  Training Step: 2590...  Training loss: 2.3825...  2.4818 sec/batch
Epoch: 7/20...  Training Step: 2591...  Training loss: 2.3667...  2.9365 sec/batch
Epoch: 7/20...  Training Step: 2592...  Training loss: 2.3675...  2.6675 sec/batch
Epoch: 7/20...  Training Step: 2593...  Training loss: 2.4090...  2.5397 sec/batch
Epoch: 7/20...  Training Step: 2594...  Training loss: 2.3797...  2.6242 sec/batch
Epoch: 7/20...  Training Step: 2595...  Training loss: 2.3803...  2.9093 sec/batch
Epoch: 7/20...  Training Step: 2596...  Training loss: 2.4019...  2.5114 sec/batch
Epoc

Epoch: 7/20...  Training Step: 2684...  Training loss: 2.3655...  2.5685 sec/batch
Epoch: 7/20...  Training Step: 2685...  Training loss: 2.3517...  2.8062 sec/batch
Epoch: 7/20...  Training Step: 2686...  Training loss: 2.3302...  2.6521 sec/batch
Epoch: 7/20...  Training Step: 2687...  Training loss: 2.3641...  2.5751 sec/batch
Epoch: 7/20...  Training Step: 2688...  Training loss: 2.3577...  2.4704 sec/batch
Epoch: 7/20...  Training Step: 2689...  Training loss: 2.3499...  2.6744 sec/batch
Epoch: 7/20...  Training Step: 2690...  Training loss: 2.3410...  2.6394 sec/batch
Epoch: 7/20...  Training Step: 2691...  Training loss: 2.3889...  2.5498 sec/batch
Epoch: 7/20...  Training Step: 2692...  Training loss: 2.3825...  2.5349 sec/batch
Epoch: 7/20...  Training Step: 2693...  Training loss: 2.3725...  2.8163 sec/batch
Epoch: 7/20...  Training Step: 2694...  Training loss: 2.3590...  2.5178 sec/batch
Epoch: 7/20...  Training Step: 2695...  Training loss: 2.3689...  2.5315 sec/batch
Epoc

Epoch: 8/20...  Training Step: 2783...  Training loss: 2.3270...  2.6267 sec/batch
Epoch: 8/20...  Training Step: 2784...  Training loss: 2.3725...  2.5242 sec/batch
Epoch: 8/20...  Training Step: 2785...  Training loss: 2.3375...  2.5191 sec/batch
Epoch: 8/20...  Training Step: 2786...  Training loss: 2.3532...  2.8366 sec/batch
Epoch: 8/20...  Training Step: 2787...  Training loss: 2.3978...  2.8595 sec/batch
Epoch: 8/20...  Training Step: 2788...  Training loss: 2.4249...  2.9259 sec/batch
Epoch: 8/20...  Training Step: 2789...  Training loss: 2.3411...  2.8484 sec/batch
Epoch: 8/20...  Training Step: 2790...  Training loss: 2.3962...  2.8790 sec/batch
Epoch: 8/20...  Training Step: 2791...  Training loss: 2.3632...  2.5509 sec/batch
Epoch: 8/20...  Training Step: 2792...  Training loss: 2.3598...  2.6429 sec/batch
Epoch: 8/20...  Training Step: 2793...  Training loss: 2.3799...  2.8556 sec/batch
Epoch: 8/20...  Training Step: 2794...  Training loss: 2.3224...  2.9134 sec/batch
Epoc

Epoch: 8/20...  Training Step: 2882...  Training loss: 2.3824...  2.9489 sec/batch
Epoch: 8/20...  Training Step: 2883...  Training loss: 2.3078...  2.7694 sec/batch
Epoch: 8/20...  Training Step: 2884...  Training loss: 2.3252...  2.6555 sec/batch
Epoch: 8/20...  Training Step: 2885...  Training loss: 2.3656...  2.7616 sec/batch
Epoch: 8/20...  Training Step: 2886...  Training loss: 2.3641...  2.9968 sec/batch
Epoch: 8/20...  Training Step: 2887...  Training loss: 2.3627...  2.6434 sec/batch
Epoch: 8/20...  Training Step: 2888...  Training loss: 2.3908...  2.6523 sec/batch
Epoch: 8/20...  Training Step: 2889...  Training loss: 2.3374...  2.8236 sec/batch
Epoch: 8/20...  Training Step: 2890...  Training loss: 2.3551...  2.9645 sec/batch
Epoch: 8/20...  Training Step: 2891...  Training loss: 2.3174...  2.9173 sec/batch
Epoch: 8/20...  Training Step: 2892...  Training loss: 2.3259...  2.7990 sec/batch
Epoch: 8/20...  Training Step: 2893...  Training loss: 2.3751...  3.1585 sec/batch
Epoc

Epoch: 8/20...  Training Step: 2981...  Training loss: 2.3482...  2.6668 sec/batch
Epoch: 8/20...  Training Step: 2982...  Training loss: 2.3387...  3.1972 sec/batch
Epoch: 8/20...  Training Step: 2983...  Training loss: 2.3593...  2.9982 sec/batch
Epoch: 8/20...  Training Step: 2984...  Training loss: 2.3274...  2.7870 sec/batch
Epoch: 8/20...  Training Step: 2985...  Training loss: 2.3597...  2.7031 sec/batch
Epoch: 8/20...  Training Step: 2986...  Training loss: 2.3122...  2.9814 sec/batch
Epoch: 8/20...  Training Step: 2987...  Training loss: 2.3459...  2.9146 sec/batch
Epoch: 8/20...  Training Step: 2988...  Training loss: 2.3333...  2.7236 sec/batch
Epoch: 8/20...  Training Step: 2989...  Training loss: 2.3322...  3.2045 sec/batch
Epoch: 8/20...  Training Step: 2990...  Training loss: 2.3704...  2.8047 sec/batch
Epoch: 8/20...  Training Step: 2991...  Training loss: 2.3548...  2.6809 sec/batch
Epoch: 8/20...  Training Step: 2992...  Training loss: 2.3537...  2.7221 sec/batch
Epoc

Epoch: 8/20...  Training Step: 3080...  Training loss: 2.3433...  2.9570 sec/batch
Epoch: 8/20...  Training Step: 3081...  Training loss: 2.3285...  2.6814 sec/batch
Epoch: 8/20...  Training Step: 3082...  Training loss: 2.3137...  2.6561 sec/batch
Epoch: 8/20...  Training Step: 3083...  Training loss: 2.2909...  2.6968 sec/batch
Epoch: 8/20...  Training Step: 3084...  Training loss: 2.3185...  2.9454 sec/batch
Epoch: 8/20...  Training Step: 3085...  Training loss: 2.3153...  2.6919 sec/batch
Epoch: 8/20...  Training Step: 3086...  Training loss: 2.3117...  2.6816 sec/batch
Epoch: 8/20...  Training Step: 3087...  Training loss: 2.3119...  2.8464 sec/batch
Epoch: 8/20...  Training Step: 3088...  Training loss: 2.3589...  3.0021 sec/batch
Epoch: 8/20...  Training Step: 3089...  Training loss: 2.3417...  2.7017 sec/batch
Epoch: 8/20...  Training Step: 3090...  Training loss: 2.3199...  2.8791 sec/batch
Epoch: 8/20...  Training Step: 3091...  Training loss: 2.3330...  2.9976 sec/batch
Epoc

Epoch: 9/20...  Training Step: 3179...  Training loss: 2.3413...  2.5616 sec/batch
Epoch: 9/20...  Training Step: 3180...  Training loss: 2.2737...  2.8156 sec/batch
Epoch: 9/20...  Training Step: 3181...  Training loss: 2.3122...  2.6470 sec/batch
Epoch: 9/20...  Training Step: 3182...  Training loss: 2.2972...  2.7479 sec/batch
Epoch: 9/20...  Training Step: 3183...  Training loss: 2.3018...  2.6967 sec/batch
Epoch: 9/20...  Training Step: 3184...  Training loss: 2.3235...  2.8568 sec/batch
Epoch: 9/20...  Training Step: 3185...  Training loss: 2.3735...  2.6329 sec/batch
Epoch: 9/20...  Training Step: 3186...  Training loss: 2.3144...  2.7652 sec/batch
Epoch: 9/20...  Training Step: 3187...  Training loss: 2.3340...  2.8486 sec/batch
Epoch: 9/20...  Training Step: 3188...  Training loss: 2.3318...  2.9711 sec/batch
Epoch: 9/20...  Training Step: 3189...  Training loss: 2.3163...  2.6660 sec/batch
Epoch: 9/20...  Training Step: 3190...  Training loss: 2.3213...  2.7871 sec/batch
Epoc

Epoch: 9/20...  Training Step: 3278...  Training loss: 2.3035...  2.6865 sec/batch
Epoch: 9/20...  Training Step: 3279...  Training loss: 2.3492...  2.7225 sec/batch
Epoch: 9/20...  Training Step: 3280...  Training loss: 2.2701...  2.8391 sec/batch
Epoch: 9/20...  Training Step: 3281...  Training loss: 2.2968...  2.5356 sec/batch
Epoch: 9/20...  Training Step: 3282...  Training loss: 2.3453...  2.5057 sec/batch
Epoch: 9/20...  Training Step: 3283...  Training loss: 2.3809...  2.5709 sec/batch
Epoch: 9/20...  Training Step: 3284...  Training loss: 2.3469...  2.8120 sec/batch
Epoch: 9/20...  Training Step: 3285...  Training loss: 2.3807...  2.5476 sec/batch
Epoch: 9/20...  Training Step: 3286...  Training loss: 2.3303...  2.5978 sec/batch
Epoch: 9/20...  Training Step: 3287...  Training loss: 2.3245...  2.6732 sec/batch
Epoch: 9/20...  Training Step: 3288...  Training loss: 2.3353...  2.8731 sec/batch
Epoch: 9/20...  Training Step: 3289...  Training loss: 2.3102...  2.5921 sec/batch
Epoc

Epoch: 9/20...  Training Step: 3377...  Training loss: 2.3485...  2.7663 sec/batch
Epoch: 9/20...  Training Step: 3378...  Training loss: 2.3152...  2.7339 sec/batch
Epoch: 9/20...  Training Step: 3379...  Training loss: 2.2958...  3.2419 sec/batch
Epoch: 9/20...  Training Step: 3380...  Training loss: 2.3357...  3.4429 sec/batch
Epoch: 9/20...  Training Step: 3381...  Training loss: 2.3124...  3.1116 sec/batch
Epoch: 9/20...  Training Step: 3382...  Training loss: 2.3283...  2.8870 sec/batch
Epoch: 9/20...  Training Step: 3383...  Training loss: 2.2889...  3.2344 sec/batch
Epoch: 9/20...  Training Step: 3384...  Training loss: 2.3148...  2.6597 sec/batch
Epoch: 9/20...  Training Step: 3385...  Training loss: 2.2978...  2.9017 sec/batch
Epoch: 9/20...  Training Step: 3386...  Training loss: 2.3005...  3.2861 sec/batch
Epoch: 9/20...  Training Step: 3387...  Training loss: 2.3367...  3.2613 sec/batch
Epoch: 9/20...  Training Step: 3388...  Training loss: 2.3146...  3.0240 sec/batch
Epoc

Epoch: 9/20...  Training Step: 3476...  Training loss: 2.2895...  2.7078 sec/batch
Epoch: 9/20...  Training Step: 3477...  Training loss: 2.3263...  2.6384 sec/batch
Epoch: 9/20...  Training Step: 3478...  Training loss: 2.3030...  2.6603 sec/batch
Epoch: 9/20...  Training Step: 3479...  Training loss: 2.3017...  2.9591 sec/batch
Epoch: 9/20...  Training Step: 3480...  Training loss: 2.2843...  2.6495 sec/batch
Epoch: 9/20...  Training Step: 3481...  Training loss: 2.3062...  2.6478 sec/batch
Epoch: 9/20...  Training Step: 3482...  Training loss: 2.2924...  2.7095 sec/batch
Epoch: 9/20...  Training Step: 3483...  Training loss: 2.3043...  3.0096 sec/batch
Epoch: 9/20...  Training Step: 3484...  Training loss: 2.2816...  2.6867 sec/batch
Epoch: 9/20...  Training Step: 3485...  Training loss: 2.3321...  2.6145 sec/batch
Epoch: 9/20...  Training Step: 3486...  Training loss: 2.3153...  2.8152 sec/batch
Epoch: 9/20...  Training Step: 3487...  Training loss: 2.2949...  2.8384 sec/batch
Epoc

Epoch: 10/20...  Training Step: 3575...  Training loss: 2.3144...  2.7962 sec/batch
Epoch: 10/20...  Training Step: 3576...  Training loss: 2.3172...  3.0139 sec/batch
Epoch: 10/20...  Training Step: 3577...  Training loss: 2.2868...  2.6586 sec/batch
Epoch: 10/20...  Training Step: 3578...  Training loss: 2.3334...  2.8108 sec/batch
Epoch: 10/20...  Training Step: 3579...  Training loss: 2.2817...  2.9601 sec/batch
Epoch: 10/20...  Training Step: 3580...  Training loss: 2.3194...  3.0168 sec/batch
Epoch: 10/20...  Training Step: 3581...  Training loss: 2.3467...  2.7068 sec/batch
Epoch: 10/20...  Training Step: 3582...  Training loss: 2.3624...  2.6626 sec/batch
Epoch: 10/20...  Training Step: 3583...  Training loss: 2.2997...  3.5194 sec/batch
Epoch: 10/20...  Training Step: 3584...  Training loss: 2.3317...  2.7710 sec/batch
Epoch: 10/20...  Training Step: 3585...  Training loss: 2.3143...  2.7619 sec/batch
Epoch: 10/20...  Training Step: 3586...  Training loss: 2.3037...  2.7185 se

Epoch: 10/20...  Training Step: 3673...  Training loss: 2.3201...  2.5735 sec/batch
Epoch: 10/20...  Training Step: 3674...  Training loss: 2.2934...  2.8870 sec/batch
Epoch: 10/20...  Training Step: 3675...  Training loss: 2.2914...  2.7804 sec/batch
Epoch: 10/20...  Training Step: 3676...  Training loss: 2.3338...  2.6692 sec/batch
Epoch: 10/20...  Training Step: 3677...  Training loss: 2.2547...  2.7262 sec/batch
Epoch: 10/20...  Training Step: 3678...  Training loss: 2.2764...  2.8585 sec/batch
Epoch: 10/20...  Training Step: 3679...  Training loss: 2.3104...  2.7804 sec/batch
Epoch: 10/20...  Training Step: 3680...  Training loss: 2.3191...  2.5362 sec/batch
Epoch: 10/20...  Training Step: 3681...  Training loss: 2.3192...  2.9423 sec/batch
Epoch: 10/20...  Training Step: 3682...  Training loss: 2.3229...  2.8166 sec/batch
Epoch: 10/20...  Training Step: 3683...  Training loss: 2.3005...  2.8939 sec/batch
Epoch: 10/20...  Training Step: 3684...  Training loss: 2.3130...  2.8768 se

Epoch: 10/20...  Training Step: 3771...  Training loss: 2.3322...  2.8431 sec/batch
Epoch: 10/20...  Training Step: 3772...  Training loss: 2.3090...  2.5801 sec/batch
Epoch: 10/20...  Training Step: 3773...  Training loss: 2.3085...  2.8048 sec/batch
Epoch: 10/20...  Training Step: 3774...  Training loss: 2.3405...  2.5339 sec/batch
Epoch: 10/20...  Training Step: 3775...  Training loss: 2.3062...  2.6050 sec/batch
Epoch: 10/20...  Training Step: 3776...  Training loss: 2.2816...  3.0182 sec/batch
Epoch: 10/20...  Training Step: 3777...  Training loss: 2.3147...  2.6707 sec/batch
Epoch: 10/20...  Training Step: 3778...  Training loss: 2.2902...  2.6934 sec/batch
Epoch: 10/20...  Training Step: 3779...  Training loss: 2.3182...  2.5323 sec/batch
Epoch: 10/20...  Training Step: 3780...  Training loss: 2.2720...  3.1302 sec/batch
Epoch: 10/20...  Training Step: 3781...  Training loss: 2.2988...  2.7434 sec/batch
Epoch: 10/20...  Training Step: 3782...  Training loss: 2.2960...  2.6458 se

Epoch: 10/20...  Training Step: 3869...  Training loss: 2.3029...  3.1369 sec/batch
Epoch: 10/20...  Training Step: 3870...  Training loss: 2.3248...  3.0329 sec/batch
Epoch: 10/20...  Training Step: 3871...  Training loss: 2.2630...  2.7299 sec/batch
Epoch: 10/20...  Training Step: 3872...  Training loss: 2.3353...  2.8329 sec/batch
Epoch: 10/20...  Training Step: 3873...  Training loss: 2.2846...  3.3476 sec/batch
Epoch: 10/20...  Training Step: 3874...  Training loss: 2.3189...  2.8322 sec/batch
Epoch: 10/20...  Training Step: 3875...  Training loss: 2.3061...  2.7670 sec/batch
Epoch: 10/20...  Training Step: 3876...  Training loss: 2.2878...  3.1975 sec/batch
Epoch: 10/20...  Training Step: 3877...  Training loss: 2.2903...  3.2319 sec/batch
Epoch: 10/20...  Training Step: 3878...  Training loss: 2.2979...  2.8310 sec/batch
Epoch: 10/20...  Training Step: 3879...  Training loss: 2.2845...  3.0693 sec/batch
Epoch: 10/20...  Training Step: 3880...  Training loss: 2.2939...  3.1021 se

Epoch: 10/20...  Training Step: 3967...  Training loss: 2.2630...  2.8367 sec/batch
Epoch: 10/20...  Training Step: 3968...  Training loss: 2.2793...  2.7378 sec/batch
Epoch: 10/20...  Training Step: 3969...  Training loss: 2.3144...  3.0437 sec/batch
Epoch: 10/20...  Training Step: 3970...  Training loss: 2.3019...  3.7534 sec/batch
Epoch: 11/20...  Training Step: 3971...  Training loss: 2.3318...  3.3793 sec/batch
Epoch: 11/20...  Training Step: 3972...  Training loss: 2.3018...  3.2453 sec/batch
Epoch: 11/20...  Training Step: 3973...  Training loss: 2.3165...  3.1052 sec/batch
Epoch: 11/20...  Training Step: 3974...  Training loss: 2.2427...  2.8924 sec/batch
Epoch: 11/20...  Training Step: 3975...  Training loss: 2.2903...  2.7783 sec/batch
Epoch: 11/20...  Training Step: 3976...  Training loss: 2.2742...  2.7456 sec/batch
Epoch: 11/20...  Training Step: 3977...  Training loss: 2.2701...  3.0468 sec/batch
Epoch: 11/20...  Training Step: 3978...  Training loss: 2.2869...  2.9033 se

Epoch: 11/20...  Training Step: 4065...  Training loss: 2.2904...  2.8372 sec/batch
Epoch: 11/20...  Training Step: 4066...  Training loss: 2.3057...  3.0881 sec/batch
Epoch: 11/20...  Training Step: 4067...  Training loss: 2.2881...  2.9572 sec/batch
Epoch: 11/20...  Training Step: 4068...  Training loss: 2.2984...  2.6567 sec/batch
Epoch: 11/20...  Training Step: 4069...  Training loss: 2.2865...  2.9051 sec/batch
Epoch: 11/20...  Training Step: 4070...  Training loss: 2.2866...  2.9317 sec/batch
Epoch: 11/20...  Training Step: 4071...  Training loss: 2.2715...  3.4859 sec/batch
Epoch: 11/20...  Training Step: 4072...  Training loss: 2.2735...  3.3995 sec/batch
Epoch: 11/20...  Training Step: 4073...  Training loss: 2.3216...  3.1094 sec/batch
Epoch: 11/20...  Training Step: 4074...  Training loss: 2.2366...  2.7738 sec/batch
Epoch: 11/20...  Training Step: 4075...  Training loss: 2.2699...  3.0958 sec/batch
Epoch: 11/20...  Training Step: 4076...  Training loss: 2.3136...  3.5858 se

Epoch: 11/20...  Training Step: 4163...  Training loss: 2.3054...  3.0813 sec/batch
Epoch: 11/20...  Training Step: 4164...  Training loss: 2.3033...  3.2671 sec/batch
Epoch: 11/20...  Training Step: 4165...  Training loss: 2.3112...  2.9003 sec/batch
Epoch: 11/20...  Training Step: 4166...  Training loss: 2.2920...  3.0382 sec/batch
Epoch: 11/20...  Training Step: 4167...  Training loss: 2.3272...  3.1866 sec/batch
Epoch: 11/20...  Training Step: 4168...  Training loss: 2.3117...  2.9743 sec/batch
Epoch: 11/20...  Training Step: 4169...  Training loss: 2.2965...  2.9918 sec/batch
Epoch: 11/20...  Training Step: 4170...  Training loss: 2.2881...  3.3695 sec/batch
Epoch: 11/20...  Training Step: 4171...  Training loss: 2.3221...  2.7665 sec/batch
Epoch: 11/20...  Training Step: 4172...  Training loss: 2.2872...  2.9446 sec/batch
Epoch: 11/20...  Training Step: 4173...  Training loss: 2.2674...  3.3368 sec/batch
Epoch: 11/20...  Training Step: 4174...  Training loss: 2.3008...  2.8286 se

Epoch: 11/20...  Training Step: 4261...  Training loss: 2.2378...  3.2525 sec/batch
Epoch: 11/20...  Training Step: 4262...  Training loss: 2.2503...  2.7381 sec/batch
Epoch: 11/20...  Training Step: 4263...  Training loss: 2.2660...  2.6809 sec/batch
Epoch: 11/20...  Training Step: 4264...  Training loss: 2.2455...  2.6832 sec/batch
Epoch: 11/20...  Training Step: 4265...  Training loss: 2.2697...  3.2711 sec/batch
Epoch: 11/20...  Training Step: 4266...  Training loss: 2.2755...  2.7762 sec/batch
Epoch: 11/20...  Training Step: 4267...  Training loss: 2.3028...  2.7274 sec/batch
Epoch: 11/20...  Training Step: 4268...  Training loss: 2.2372...  2.8766 sec/batch
Epoch: 11/20...  Training Step: 4269...  Training loss: 2.3062...  2.8976 sec/batch
Epoch: 11/20...  Training Step: 4270...  Training loss: 2.2610...  3.0336 sec/batch
Epoch: 11/20...  Training Step: 4271...  Training loss: 2.2955...  2.8349 sec/batch
Epoch: 11/20...  Training Step: 4272...  Training loss: 2.2755...  3.0652 se

Epoch: 11/20...  Training Step: 4359...  Training loss: 2.2730...  3.1826 sec/batch
Epoch: 11/20...  Training Step: 4360...  Training loss: 2.3002...  3.0012 sec/batch
Epoch: 11/20...  Training Step: 4361...  Training loss: 2.2770...  2.9891 sec/batch
Epoch: 11/20...  Training Step: 4362...  Training loss: 2.2652...  2.8591 sec/batch
Epoch: 11/20...  Training Step: 4363...  Training loss: 2.2664...  3.5053 sec/batch
Epoch: 11/20...  Training Step: 4364...  Training loss: 2.2498...  3.4727 sec/batch
Epoch: 11/20...  Training Step: 4365...  Training loss: 2.2556...  3.2982 sec/batch
Epoch: 11/20...  Training Step: 4366...  Training loss: 2.2992...  3.2177 sec/batch
Epoch: 11/20...  Training Step: 4367...  Training loss: 2.2857...  2.7994 sec/batch
Epoch: 12/20...  Training Step: 4368...  Training loss: 2.2961...  2.9542 sec/batch
Epoch: 12/20...  Training Step: 4369...  Training loss: 2.2602...  3.2644 sec/batch
Epoch: 12/20...  Training Step: 4370...  Training loss: 2.2875...  2.7638 se

Epoch: 12/20...  Training Step: 4457...  Training loss: 2.2821...  3.4169 sec/batch
Epoch: 12/20...  Training Step: 4458...  Training loss: 2.2827...  3.3729 sec/batch
Epoch: 12/20...  Training Step: 4459...  Training loss: 2.2322...  3.3343 sec/batch
Epoch: 12/20...  Training Step: 4460...  Training loss: 2.2924...  3.2120 sec/batch
Epoch: 12/20...  Training Step: 4461...  Training loss: 2.3062...  3.3233 sec/batch
Epoch: 12/20...  Training Step: 4462...  Training loss: 2.2910...  3.4099 sec/batch
Epoch: 12/20...  Training Step: 4463...  Training loss: 2.3021...  3.2846 sec/batch
Epoch: 12/20...  Training Step: 4464...  Training loss: 2.2847...  3.2313 sec/batch
Epoch: 12/20...  Training Step: 4465...  Training loss: 2.2985...  2.9826 sec/batch
Epoch: 12/20...  Training Step: 4466...  Training loss: 2.2723...  3.1954 sec/batch
Epoch: 12/20...  Training Step: 4467...  Training loss: 2.2845...  3.2520 sec/batch
Epoch: 12/20...  Training Step: 4468...  Training loss: 2.2679...  3.0716 se

Epoch: 12/20...  Training Step: 4555...  Training loss: 2.2479...  2.9074 sec/batch
Epoch: 12/20...  Training Step: 4556...  Training loss: 2.2479...  3.4813 sec/batch
Epoch: 12/20...  Training Step: 4557...  Training loss: 2.2440...  3.1158 sec/batch
Epoch: 12/20...  Training Step: 4558...  Training loss: 2.2550...  2.9445 sec/batch
Epoch: 12/20...  Training Step: 4559...  Training loss: 2.3158...  2.9047 sec/batch
Epoch: 12/20...  Training Step: 4560...  Training loss: 2.3025...  3.3716 sec/batch
Epoch: 12/20...  Training Step: 4561...  Training loss: 2.2939...  2.8862 sec/batch
Epoch: 12/20...  Training Step: 4562...  Training loss: 2.3098...  2.7015 sec/batch
Epoch: 12/20...  Training Step: 4563...  Training loss: 2.2864...  3.0777 sec/batch
Epoch: 12/20...  Training Step: 4564...  Training loss: 2.3156...  2.8795 sec/batch
Epoch: 12/20...  Training Step: 4565...  Training loss: 2.3056...  3.2083 sec/batch
Epoch: 12/20...  Training Step: 4566...  Training loss: 2.2953...  2.9061 se

Epoch: 12/20...  Training Step: 4653...  Training loss: 2.2471...  2.6189 sec/batch
Epoch: 12/20...  Training Step: 4654...  Training loss: 2.2595...  2.6347 sec/batch
Epoch: 12/20...  Training Step: 4655...  Training loss: 2.2654...  3.0199 sec/batch
Epoch: 12/20...  Training Step: 4656...  Training loss: 2.2664...  3.0570 sec/batch
Epoch: 12/20...  Training Step: 4657...  Training loss: 2.2323...  2.7125 sec/batch
Epoch: 12/20...  Training Step: 4658...  Training loss: 2.2307...  2.7020 sec/batch
Epoch: 12/20...  Training Step: 4659...  Training loss: 2.2432...  3.1075 sec/batch
Epoch: 12/20...  Training Step: 4660...  Training loss: 2.2595...  2.9485 sec/batch
Epoch: 12/20...  Training Step: 4661...  Training loss: 2.2362...  2.8212 sec/batch
Epoch: 12/20...  Training Step: 4662...  Training loss: 2.2648...  2.8082 sec/batch
Epoch: 12/20...  Training Step: 4663...  Training loss: 2.2636...  2.8927 sec/batch
Epoch: 12/20...  Training Step: 4664...  Training loss: 2.3031...  2.8416 se

KeyboardInterrupt: 

#### Saved checkpoints

Read up on saving and loading checkpoints here: https://www.tensorflow.org/programmers_guide/variables

In [ ]:
tf.train.get_checkpoint_state('checkpoints')

In [19]:
print(tf.__version__)

1.1.0


## Sampling

Now that the network is trained, we'll can use it to generate new text. The idea is that we pass in a character, then the network will predict the next character. We can use the new one, to predict the next one. And we keep doing this to generate all new text. I also included some functionality to prime the network with some text by passing in a string and building up a state from that.

The network gives us predictions for each character. To reduce noise and make things a little less random, I'm going to only choose a new character from the top N most likely characters.



In [ ]:
def pick_top_n(preds, vocab_size, top_n=5):
    p = np.squeeze(preds)
    p[np.argsort(p)[:-top_n]] = 0
    p = p / np.sum(p)
    c = np.random.choice(vocab_size, 1, p=p)[0]
    return c

In [ ]:
def sample(checkpoint, n_samples, lstm_size, vocab_size, prime="The "):
    samples = [c for c in prime]
    model = CharRNN(len(vocab), lstm_size=lstm_size, sampling=True)
    saver = tf.train.Saver()
    with tf.Session() as sess:
        saver.restore(sess, checkpoint)
        new_state = sess.run(model.initial_state)
        for c in prime:
            x = np.zeros((1, 1))
            x[0,0] = vocab_to_int[c]
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

        c = pick_top_n(preds, len(vocab))
        samples.append(int_to_vocab[c])

        for i in range(n_samples):
            x[0,0] = c
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

            c = pick_top_n(preds, len(vocab))
            samples.append(int_to_vocab[c])
        
    return ''.join(samples)

Here, pass in the path to a checkpoint and sample from the network.

In [ ]:
tf.train.latest_checkpoint('checkpoints')

In [ ]:
checkpoint = tf.train.latest_checkpoint('checkpoints')
samp = sample(checkpoint, 2000, lstm_size, len(vocab), prime="Far")
print(samp)

In [ ]:
checkpoint = 'checkpoints/i200_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

In [ ]:
checkpoint = 'checkpoints/i600_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

In [ ]:
checkpoint = 'checkpoints/i1200_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)